## Combines responses across phenotypes for further analysis
## In human samples. 
## Eloise Pariset, USRA/NASA Ames, March 2020
## For all runs on this project, without duplicates for DNA damage

## To be expanded (in the same file) by adding DNA damage data on BNL18B and BNL19C, and potentially duplicates


```{r}
require('lattice')
require('ggplot2')
require('polynom')
require('plyr')
require('reshape2')
require('stringr')
require('dplyr')
library('proj4')
require('ggalt')
library(IDPmisc)

```

```{r}
theme_set(theme_bw(base_size = 12)) ## For prettier graphs
theme_update(plot.title = element_text(hjust = 0.5))
setwd(getwd())
```

## Read DNA damage data BNL19A
```{r}
gamma_plate_nums_19A = c(433, 435, 437, 439, 441, 444, 445, 447, 449, 451, 453, 455, 457, 459, 461, 463, 465, 467, 469, 471, 473, 475, 477,479)
gamma_plate_count_19A = length(gamma_plate_nums_19A)
ar_plate_nums_19A = c(481, 483, 485, 487, 489, 491, 493, 495, 497, 499, 501, 503, 505, 507, 509, 511, 513, 515, 517, 519, 521, 523, 525,527)
ar_plate_count_19A = length(ar_plate_nums_19A)
si_plate_nums_19A = c(577, 579, 581, 583, 585, 587, 589, 591, 593, 595, 597, 599, 601, 603, 605,607, 609, 611, 613,615, 617, 619, 621, 623)
si_plate_count_19A = length(si_plate_nums_19A)
fe_plate_nums_19A = c(529, 531, 533, 535, 537, 539, 541, 543, 545, 547, 549, 551, 553, 555, 557, 559, 561, 563, 565, 567, 569, 571, 573,575)
fe_plate_count_19A = length(fe_plate_nums_19A)
gamma_si_fe_ar_plate_nums_19A = c(gamma_plate_nums_19A, si_plate_nums_19A, fe_plate_nums_19A, ar_plate_nums_19A)
gamma_si_fe_ar_plate_count_19A = length(gamma_si_fe_ar_plate_nums_19A)
```

```{r}
## Read first file
foci_gamma_first_19A = data.frame(Plate = gamma_plate_nums_19A[1], Plate_well = paste(gamma_plate_nums_19A[1], read.table(paste("average_well/BNL19A/average_well_P", gamma_plate_nums_19A[1],'.txt', sep=""), sep="\t", header = TRUE)$Well, sep = "_"), read.table(paste("average_well/BNL19A/average_well_P", gamma_plate_nums_19A[1],'.txt', sep=""), sep="\t", header = TRUE))

gamma_table_19A=foci_gamma_first_19A

foci_si_first_19A = data.frame(Plate = si_plate_nums_19A[1], Plate_well = paste(si_plate_nums_19A[1], read.table(paste("average_well/BNL19A/average_well_P", si_plate_nums_19A[1],'.txt', sep=""), sep="\t", header = TRUE)$Well, sep = "_"), read.table(paste("average_well/BNL19A/average_well_P", si_plate_nums_19A[1],'.txt', sep=""), sep="\t", header = TRUE))

si_table_19A=foci_si_first_19A

foci_ar_first_19A = data.frame(Plate = ar_plate_nums_19A[1], Plate_well = paste(ar_plate_nums_19A[1], read.table(paste("average_well/BNL19A/average_well_P", ar_plate_nums_19A[1],'.txt', sep=""), sep="\t", header = TRUE)$Well, sep = "_"), read.table(paste("average_well/BNL19A/average_well_P", ar_plate_nums_19A[1],'.txt', sep=""), sep="\t", header = TRUE))

ar_table_19A=foci_ar_first_19A

foci_fe_first_19A = data.frame(Plate = fe_plate_nums_19A[1], Plate_well = paste(fe_plate_nums_19A[1], read.table(paste("average_well/BNL19A/average_well_P", fe_plate_nums_19A[1],'.txt', sep=""), sep="\t", header = TRUE)$Well, sep = "_"), read.table(paste("average_well/BNL19A/average_well_P", fe_plate_nums_19A[1],'.txt', sep=""), sep="\t", header = TRUE))

fe_table_19A=foci_fe_first_19A
```

```{r}
## Read all the other files and combine them into a single giant file with ALL the plates and ALL the wells
for(ii in 2:gamma_plate_count_19A){
  temp_gamma_filename = paste('average_well/BNL19A/average_well_P', gamma_plate_nums_19A[ii],'.txt', sep="")
  temp_gamma_table = data.frame(Plate = gamma_plate_nums_19A[ii], Plate_well = paste(gamma_plate_nums_19A[ii], read.table(paste('average_well/BNL19A/average_well_P', gamma_plate_nums_19A[ii],'.txt', sep=""), sep="\t", header = TRUE)$Well, sep = "_"), read.table(paste('average_well/BNL19A/average_well_P', gamma_plate_nums_19A[ii],'.txt', sep=""), sep="\t", header = TRUE))
  gamma_table_19A = rbind(gamma_table_19A, temp_gamma_table)
}

for(ii in 2:si_plate_count_19A){
  temp_si_filename = paste('average_well/BNL19A/average_well_P', si_plate_nums_19A[ii],'.txt', sep="")
  temp_si_table = data.frame(Plate = si_plate_nums_19A[ii], Plate_well = paste(si_plate_nums_19A[ii], read.table(paste('average_well/BNL19A/average_well_P', si_plate_nums_19A[ii],'.txt', sep=""), sep="\t", header = TRUE)$Well, sep = "_"), read.table(paste('average_well/BNL19A/average_well_P', si_plate_nums_19A[ii],'.txt', sep=""), sep="\t", header = TRUE))
  si_table_19A = rbind(si_table_19A, temp_si_table)
}

for(ii in 2:ar_plate_count_19A){
  temp_ar_filename = paste('average_well/BNL19A/average_well_P', ar_plate_nums_19A[ii],'.txt', sep="")
  temp_ar_table = data.frame(Plate = ar_plate_nums_19A[ii], Plate_well = paste(ar_plate_nums_19A[ii], read.table(paste('average_well/BNL19A/average_well_P', ar_plate_nums_19A[ii],'.txt', sep=""), sep="\t", header = TRUE)$Well, sep = "_"), read.table(paste('average_well/BNL19A/average_well_P', ar_plate_nums_19A[ii],'.txt', sep=""), sep="\t", header = TRUE))
  ar_table_19A = rbind(ar_table_19A, temp_ar_table)
  }

for(ii in 2:fe_plate_count_19A){
  temp_fe_filename = paste('average_well/BNL19A/average_well_P', fe_plate_nums_19A[ii],'.txt', sep="")
  temp_fe_table = data.frame(Plate = fe_plate_nums_19A[ii], Plate_well = paste(fe_plate_nums_19A[ii], read.table(paste('average_well/BNL19A/average_well_P', fe_plate_nums_19A[ii],'.txt', sep=""), sep="\t", header = TRUE)$Well, sep = "_"), read.table(paste('average_well/BNL19A/average_well_P', fe_plate_nums_19A[ii],'.txt', sep=""), sep="\t", header = TRUE))
  fe_table_19A = rbind(fe_table_19A, temp_fe_table)
  }
```

## Read DNA damage data BNL18B
```{r}
ar_plate_nums_18B = c(381,382,383,386,387,390,391,394,395,396,399,400,402) # To save time, only one duplicate was imaged, unless values of foci were unconsistent with the other data
ar_plate_count_18B = length(ar_plate_nums_18B)
si_plate_nums_18B = c(333,337,341,345,349,353) # To save time, only one duplicate was imaged, unless values of foci were unconsistent with the other data
si_plate_count_18B = length(si_plate_nums_18B)
fe_plate_nums_18B = c(355,356,357,358,359,360,361,362,363,364,365,366,367,368,369,370,372,373,374,375,376,377,378) # We exclude P371 (0Gy 4h Set1A) because of very low avg_nfoci compared to duplicate P373
fe_plate_count_18B = length(fe_plate_nums_18B)
fe_ar_plate_nums_18B = c(fe_plate_nums_18B, ar_plate_nums_18B)
fe_ar_plate_count_18B = length(fe_ar_plate_nums_18B)
```

```{r}
## Read first file
foci_ar_first_18B = data.frame(Plate = ar_plate_nums_18B[1], Plate_well = paste(ar_plate_nums_18B[1], read.table(paste("average_well/BNL18B/average_well_P", ar_plate_nums_18B[1],'.txt', sep=""), sep="\t", header = TRUE)$Well, sep = "_"), read.table(paste("average_well/BNL18B/average_well_P", ar_plate_nums_18B[1],'.txt', sep=""), sep="\t", header = TRUE))

ar_table_18B=foci_ar_first_18B

foci_si_first_18B = data.frame(Plate = si_plate_nums_18B[1], Plate_well = paste(si_plate_nums_18B[1], read.table(paste("average_well/BNL18B/average_well_P", si_plate_nums_18B[1],'.txt', sep=""), sep="\t", header = TRUE)$Well, sep = "_"), read.table(paste("average_well/BNL18B/average_well_P", si_plate_nums_18B[1],'.txt', sep=""), sep="\t", header = TRUE))

si_table_18B=foci_si_first_18B

foci_fe_first_18B = data.frame(Plate = fe_plate_nums_18B[1], Plate_well = paste(fe_plate_nums_18B[1], read.table(paste("average_well/BNL18B/average_well_P", fe_plate_nums_18B[1],'.txt', sep=""), sep="\t", header = TRUE)$Well, sep = "_"), read.table(paste("average_well/BNL18B/average_well_P", fe_plate_nums_18B[1],'.txt', sep=""), sep="\t", header = TRUE))

fe_table_18B=foci_fe_first_18B
```

```{r}
## Read all the other files and combine them into a single giant file with ALL the plates and ALL the wells
for(ii in 2:ar_plate_count_18B){
  temp_ar_filename = paste('average_well/BNL18B/average_well_P', ar_plate_nums_18B[ii],'.txt', sep="")
  temp_ar_table = data.frame(Plate = ar_plate_nums_18B[ii], Plate_well = paste(ar_plate_nums_18B[ii], read.table(paste('average_well/BNL18B/average_well_P', ar_plate_nums_18B[ii],'.txt', sep=""), sep="\t", header = TRUE)$Well, sep = "_"), read.table(paste('average_well/BNL18B/average_well_P', ar_plate_nums_18B[ii],'.txt', sep=""), sep="\t", header = TRUE))
  ar_table_18B = rbind(ar_table_18B, temp_ar_table)
  }

for(ii in 2:si_plate_count_18B){
  temp_si_filename = paste('average_well/BNL18B/average_well_P', si_plate_nums_18B[ii],'.txt', sep="")
  temp_si_table = data.frame(Plate = si_plate_nums_18B[ii], Plate_well = paste(si_plate_nums_18B[ii], read.table(paste('average_well/BNL18B/average_well_P', si_plate_nums_18B[ii],'.txt', sep=""), sep="\t", header = TRUE)$Well, sep = "_"), read.table(paste('average_well/BNL18B/average_well_P', si_plate_nums_18B[ii],'.txt', sep=""), sep="\t", header = TRUE))
  si_table_18B = rbind(si_table_18B, temp_si_table)
  }

for(ii in 2:fe_plate_count_18B){
  temp_fe_filename = paste('average_well/BNL18B/average_well_P', fe_plate_nums_18B[ii],'.txt', sep="")
  temp_fe_table = data.frame(Plate = fe_plate_nums_18B[ii], Plate_well = paste(fe_plate_nums_18B[ii], read.table(paste('average_well/BNL18B/average_well_P', fe_plate_nums_18B[ii],'.txt', sep=""), sep="\t", header = TRUE)$Well, sep = "_"), read.table(paste('/Users/epariset/Desktop/Processed-all/BNL18B-ProcessedFile/Fe-BNL_18B-reprocessed/average_well_P', fe_plate_nums_18B[ii],'.txt', sep=""), sep="\t", header = TRUE))
  fe_table_18B = rbind(fe_table_18B, temp_fe_table)
  }
```

```{r}
## We combine 18B and 19A data
ar_table = rbind(ar_table_18B, ar_table_19A)
fe_table = rbind(fe_table_18B, fe_table_19A)
si_table = rbind(si_table_18B, si_table_19A)
gamma_table = gamma_table_19A
```

```{r}
## Now we will add plate metadata
plate_meta = read.csv('Plate_metadata.csv', sep = ",", header = TRUE)
fe_table_w_plate_meta = merge(fe_table, plate_meta, by.x = 'Plate', by.y = 'Plate_number', all.x = TRUE, all.y = FALSE)
ar_table_w_plate_meta = merge(ar_table, plate_meta, by.x = 'Plate', by.y = 'Plate_number', all.x = TRUE, all.y = FALSE)
si_table_w_plate_meta = merge(si_table, plate_meta, by.x = 'Plate', by.y = 'Plate_number', all.x = TRUE, all.y = FALSE)
gamma_table_w_plate_meta = merge(gamma_table, plate_meta, by.x = 'Plate', by.y = 'Plate_number', all.x = TRUE, all.y = FALSE)

# Wells are different based on sample sets, so we need to make an extra column for Set_Well, and then add well metadata based on it.
fe_table_w_plate_meta$Run_set_well = paste(fe_table_w_plate_meta$Run, fe_table_w_plate_meta$Sample_sets, fe_table_w_plate_meta$Well, sep = "_")
ar_table_w_plate_meta$Run_set_well = paste(ar_table_w_plate_meta$Run, ar_table_w_plate_meta$Sample_sets, ar_table_w_plate_meta$Well, sep = "_")
si_table_w_plate_meta$Run_set_well = paste(si_table_w_plate_meta$Run, si_table_w_plate_meta$Sample_sets, si_table_w_plate_meta$Well, sep = "_")
gamma_table_w_plate_meta$Run_set_well = paste(gamma_table_w_plate_meta$Run, gamma_table_w_plate_meta$Sample_sets, gamma_table_w_plate_meta$Well, sep = "_")
```

```{r}
# Set low bar. This is arbitrary! We will ask for at least 50 imaged nuclei per well to consider that well. 
low_bar = 50
fe_filt = fe_table_w_plate_meta[fe_table_w_plate_meta$num_nuc > (low_bar-1),]
ar_filt = ar_table_w_plate_meta[ar_table_w_plate_meta$num_nuc > (low_bar-1),]
si_filt = si_table_w_plate_meta[si_table_w_plate_meta$num_nuc > (low_bar-1),]
gamma_filt = gamma_table_w_plate_meta[gamma_table_w_plate_meta$num_nuc > (low_bar-1),]
```

```{r}
# Truncate dataframe to only include the columns of interest
col_trunc = c("Run_set_well", "avg_nfoci", "Dose_Fluence", "Timepoint")
fe_trunc = fe_filt[,colnames(fe_filt) %in% col_trunc]

col_trunc = c("Run_set_well", "avg_nfoci", "Dose_Fluence", "Timepoint")
ar_trunc = ar_filt[,colnames(ar_filt) %in% col_trunc]

col_trunc = c("Run_set_well", "avg_nfoci", "Dose_Fluence", "Timepoint")
si_trunc = si_filt[,colnames(si_filt) %in% col_trunc]

col_trunc = c("Run_set_well", "avg_nfoci", "Dose_Fluence", "Timepoint")
gamma_trunc = gamma_filt[,colnames(gamma_filt) %in% col_trunc]
```

```{r}
# Now we will need to average A and B duplicates
fe_avg = ddply(fe_trunc, .(Run_set_well, Dose_Fluence, Timepoint), summarise, avg_nfoci = mean(avg_nfoci))

ar_avg = ddply(ar_trunc, .(Run_set_well, Dose_Fluence, Timepoint), summarise, avg_nfoci = mean(avg_nfoci))

si_avg = ddply(si_trunc, .(Run_set_well, Dose_Fluence, Timepoint), summarise, avg_nfoci = mean(avg_nfoci))

gamma_avg = ddply(gamma_trunc, .(Run_set_well, Dose_Fluence, Timepoint), summarise, avg_nfoci = mean(avg_nfoci))
```

```{r}
# Now we combine all ions in a single matrix

## For Fe:
fe_reshaped <- dcast(fe_avg, Run_set_well + Timepoint ~ Dose_Fluence, value.var = 'avg_nfoci')
colnames(fe_reshaped)[colnames(fe_reshaped) == "0"] = "Fe_avg_nfoci_0"
colnames(fe_reshaped)[colnames(fe_reshaped) == "1.1"] = "Fe_avg_nfoci_1"
colnames(fe_reshaped)[colnames(fe_reshaped) == "3"] = "Fe_avg_nfoci_3"

fe_reshaped_4h = fe_reshaped[fe_reshaped$Timepoint == "4h",]
colnames(fe_reshaped_4h)[colnames(fe_reshaped_4h) == "Fe_avg_nfoci_0"] = "Fe_avg_nfoci_0_4h"
colnames(fe_reshaped_4h)[colnames(fe_reshaped_4h) == "Fe_avg_nfoci_1"] = "Fe_avg_nfoci_1_4h"
colnames(fe_reshaped_4h)[colnames(fe_reshaped_4h) == "Fe_avg_nfoci_3"] = "Fe_avg_nfoci_3_4h"

fe_reshaped_24h = fe_reshaped[fe_reshaped$Timepoint == "24h",]
colnames(fe_reshaped_24h)[colnames(fe_reshaped_24h) == "Fe_avg_nfoci_0"] = "Fe_avg_nfoci_0_24h"
colnames(fe_reshaped_24h)[colnames(fe_reshaped_24h) == "Fe_avg_nfoci_1"] = "Fe_avg_nfoci_1_24h"
colnames(fe_reshaped_24h)[colnames(fe_reshaped_24h) == "Fe_avg_nfoci_3"] = "Fe_avg_nfoci_3_24h"

fe_temp = merge(fe_reshaped_4h, fe_reshaped_24h, by.x = 'Run_set_well', by.y = 'Run_set_well')

cols_to_drop = c('Timepoint.x','Timepoint.y')
fe_all = fe_temp[, !colnames(fe_temp) %in% cols_to_drop]

## For Ar:
ar_reshaped <- dcast(ar_avg, Run_set_well + Timepoint ~ Dose_Fluence, value.var = 'avg_nfoci')
colnames(ar_reshaped)[colnames(ar_reshaped) == "0"] = "Ar_avg_nfoci_0"
colnames(ar_reshaped)[colnames(ar_reshaped) == "1.1"] = "Ar_avg_nfoci_1"
colnames(ar_reshaped)[colnames(ar_reshaped) == "3"] = "Ar_avg_nfoci_3"

ar_reshaped_4h = ar_reshaped[ar_reshaped$Timepoint == "4h",]
colnames(ar_reshaped_4h)[colnames(ar_reshaped_4h) == "Ar_avg_nfoci_0"] = "Ar_avg_nfoci_0_4h"
colnames(ar_reshaped_4h)[colnames(ar_reshaped_4h) == "Ar_avg_nfoci_1"] = "Ar_avg_nfoci_1_4h"
colnames(ar_reshaped_4h)[colnames(ar_reshaped_4h) == "Ar_avg_nfoci_3"] = "Ar_avg_nfoci_3_4h"

ar_reshaped_24h = ar_reshaped[ar_reshaped$Timepoint == "24h",]
colnames(ar_reshaped_24h)[colnames(ar_reshaped_24h) == "Ar_avg_nfoci_0"] = "Ar_avg_nfoci_0_24h"
colnames(ar_reshaped_24h)[colnames(ar_reshaped_24h) == "Ar_avg_nfoci_1"] = "Ar_avg_nfoci_1_24h"
colnames(ar_reshaped_24h)[colnames(ar_reshaped_24h) == "Ar_avg_nfoci_3"] = "Ar_avg_nfoci_3_24h"

ar_temp = merge(ar_reshaped_4h, ar_reshaped_24h, by.x = 'Run_set_well', by.y = 'Run_set_well')

cols_to_drop = c('Timepoint.x','Timepoint.y')
ar_all = ar_temp[, !colnames(ar_temp) %in% cols_to_drop]

## For Si:
si_reshaped <- dcast(si_avg, Run_set_well + Timepoint ~ Dose_Fluence, value.var = 'avg_nfoci')
colnames(si_reshaped)[colnames(si_reshaped) == "0"] = "Si_avg_nfoci_0"
colnames(si_reshaped)[colnames(si_reshaped) == "1.1"] = "Si_avg_nfoci_1"
colnames(si_reshaped)[colnames(si_reshaped) == "3"] = "Si_avg_nfoci_3"

si_reshaped_4h = si_reshaped[si_reshaped$Timepoint == "4h",]
colnames(si_reshaped_4h)[colnames(si_reshaped_4h) == "Si_avg_nfoci_0"] = "Si_avg_nfoci_0_4h"
colnames(si_reshaped_4h)[colnames(si_reshaped_4h) == "Si_avg_nfoci_1"] = "Si_avg_nfoci_1_4h"
colnames(si_reshaped_4h)[colnames(si_reshaped_4h) == "Si_avg_nfoci_3"] = "Si_avg_nfoci_3_4h"

si_reshaped_24h = si_reshaped[si_reshaped$Timepoint == "24h",]
colnames(si_reshaped_24h)[colnames(si_reshaped_24h) == "Si_avg_nfoci_0"] = "Si_avg_nfoci_0_24h"
colnames(si_reshaped_24h)[colnames(si_reshaped_24h) == "Si_avg_nfoci_1"] = "Si_avg_nfoci_1_24h"
colnames(si_reshaped_24h)[colnames(si_reshaped_24h) == "Si_avg_nfoci_3"] = "Si_avg_nfoci_3_24h"

si_temp = merge(si_reshaped_4h, si_reshaped_24h, by.x = 'Run_set_well', by.y = 'Run_set_well')

cols_to_drop = c('Timepoint.x','Timepoint.y')
si_all = si_temp[, !colnames(si_temp) %in% cols_to_drop]

## For Gamma:
gamma_reshaped <- dcast(gamma_avg, Run_set_well + Timepoint ~ Dose_Fluence, value.var = 'avg_nfoci')
colnames(gamma_reshaped)[colnames(gamma_reshaped) == "0"] = "Gamma_avg_nfoci_0"
colnames(gamma_reshaped)[colnames(gamma_reshaped) == "0.1"] = "Gamma_avg_nfoci_0.1"
colnames(gamma_reshaped)[colnames(gamma_reshaped) == "1"] = "Gamma_avg_nfoci_1"

gamma_reshaped_4h = gamma_reshaped[gamma_reshaped$Timepoint == "4h",]
colnames(gamma_reshaped_4h)[colnames(gamma_reshaped_4h) == "Gamma_avg_nfoci_0"] = "Gamma_avg_nfoci_0_4h"
colnames(gamma_reshaped_4h)[colnames(gamma_reshaped_4h) == "Gamma_avg_nfoci_0.1"] = "Gamma_avg_nfoci_0.1_4h"
colnames(gamma_reshaped_4h)[colnames(gamma_reshaped_4h) == "Gamma_avg_nfoci_1"] = "Gamma_avg_nfoci_1_4h"

gamma_reshaped_24h = gamma_reshaped[gamma_reshaped$Timepoint == "24h",]
colnames(gamma_reshaped_24h)[colnames(gamma_reshaped_24h) == "Gamma_avg_nfoci_0"] = "Gamma_avg_nfoci_0_24h"
colnames(gamma_reshaped_24h)[colnames(gamma_reshaped_24h) == "Gamma_avg_nfoci_0.1"] = "Gamma_avg_nfoci_0.1_24h"
colnames(gamma_reshaped_24h)[colnames(gamma_reshaped_24h) == "Gamma_avg_nfoci_1"] = "Gamma_avg_nfoci_1_24h"

gamma_temp = merge(gamma_reshaped_4h, gamma_reshaped_24h, by.x = 'Run_set_well', by.y = 'Run_set_well')

cols_to_drop = c('Timepoint.x','Timepoint.y')
gamma_all = gamma_temp[, !colnames(gamma_temp) %in% cols_to_drop]

all_RIF = merge(fe_all, ar_all, by.x = 'Run_set_well', by.y = 'Run_set_well', all=TRUE)
all_RIF = merge(all_RIF, si_all, by.x = 'Run_set_well', by.y = 'Run_set_well', all=TRUE)
all_RIF = merge(all_RIF, gamma_all, by.x = 'Run_set_well', by.y = 'Run_set_well', all=TRUE)
```

```{r}
# Now we add well metadata
well_meta = read.csv('Well_metadata.csv', sep = ",", header = TRUE)
all_RIF_meta = merge(all_RIF, well_meta, by.x = 'Run_set_well', by.y = 'Run_set_well')
```

## Read flow data

```{r}
## Read all flow data, which in this case includes metadata of CellROX intensity and cell death percentage in WIDE format
flow_all = read.csv('all_flow.csv', sep = ",", header = TRUE)
colnames(flow_all)[colnames(flow_all) == "ï..Sample_ID"] = "Sample_ID"
```

```{r}
# Now we combine all ions in a single matrix and create decay metrics

all_flow_4h = flow_all[flow_all$Timepoint == "4h",]
colnames(all_flow_4h)=paste(colnames(all_flow_4h),"4h",sep="_")

all_flow_24h = flow_all[flow_all$Timepoint == "24h",]
colnames(all_flow_24h)=paste(colnames(all_flow_24h),"24h",sep="_")

all_flow_temp = merge(all_flow_4h, all_flow_24h, by.x = 'Sample_ID_4h', by.y = 'Sample_ID_24h', all = TRUE)
colnames(all_flow_temp)[colnames(all_flow_temp) == "Sample_ID_4h"] = "Sample_ID"

cols_to_drop = c('Timepoint_4h','Timepoint_24h','Sample_ID_24h')
all_flow_temp = all_flow_temp[, !colnames(all_flow_temp) %in% cols_to_drop]

all_flow = all_flow_temp
```

```{r}
# Now we add well metadata
all_flow_meta = merge(all_flow, well_meta, by.x = 'Sample_ID', by.y = 'Sample_ID')
```

```{r}
# Now we add baseline avg_nfoci
baseline_plate_nums = c(319,320,321,322,323,324,428, 429, 430, 431, 432, 625, 626, 627, 628, 629, 630)
baseline_plate_count = length(baseline_plate_nums)

subject_meta = read.csv('Baseline_metadata.csv', sep = ",", header = TRUE)
subject_ids = unique(subject_meta$Sample_ID)
num_subj = length(subject_ids)
plate_meta = read.csv('Baseline_plate_metadata.csv', sep = ",", header = TRUE)
plate_ids = unique(plate_meta$Plate_number)
num_plate = length(plate_ids)

foci_baseline_first = data.frame(Plate = baseline_plate_nums[1], Plate_well = paste(baseline_plate_nums[1], read.table(paste("average_well/Baselines/average_well_P", baseline_plate_nums[1],'.txt', sep=""), sep="\t", header = TRUE)$Well, sep = "_"), read.table(paste("average_well/Baselines/average_well_P", baseline_plate_nums[1],'.txt', sep=""), sep="\t", header = TRUE))
baseline_table=foci_baseline_first

for(ii in 2:baseline_plate_count){
  temp_baseline_filename = paste('average_well/Baselines/average_well_P', baseline_plate_nums[ii],'.txt', sep="")
  temp_baseline_table = data.frame(Plate = baseline_plate_nums[ii], Plate_well = paste(baseline_plate_nums[ii], read.table(paste('average_well/Baselines/average_well_P', baseline_plate_nums[ii],'.txt', sep=""), sep="\t", header = TRUE)$Well, sep = "_"), read.table(paste('average_well/Baselines/average_well_P', baseline_plate_nums[ii],'.txt', sep=""), sep="\t", header = TRUE))
  baseline_table = rbind(baseline_table, temp_baseline_table)
}

baseline_w_plate_meta1 = merge(baseline_table, plate_meta, by.x = 'Plate', by.y = 'Plate_number', all.x = TRUE, all.y = TRUE)
baseline_w_plate_meta = merge(baseline_w_plate_meta1, subject_meta, by.x = 'Plate_well', by.y = 'Plate_Well', all.x = TRUE, all.y = TRUE)
colnames(baseline_w_plate_meta)[colnames(baseline_w_plate_meta)=="Plate.x"]<-"Plate"
colnames(baseline_w_plate_meta)[colnames(baseline_w_plate_meta)=="Well.x"]<-"Well"
#write.csv(baseline_w_plate_meta,"Baseline_Raw_Data_No_Threshold.csv")

low_bar = 50
baseline_filt = baseline_w_plate_meta[baseline_w_plate_meta$num_nuc > (low_bar-1),]

baseline_filt_2 = baseline_filt[baseline_filt$avg_nfoci != 0,]
#write.csv(baseline_filt_2,"all_baseline_raw_filt50_06302020.csv")


subject_meta_avg = read.csv('Baseline_metadata_avg.csv', sep = ",", header = TRUE)
baseline_avgfoci_temp <- baseline_filt_2 %>% group_by(Sample_ID) %>% summarize(avg_nfoci_mean = mean(avg_nfoci))
colnames(baseline_avgfoci_temp)[colnames(baseline_avgfoci_temp)=="avg_nfoci_mean"]<-"avg_nfoci"
baseline_avgfoci = distinct(merge(baseline_avgfoci_temp, subject_meta_avg, by.x = 'Sample_ID', by.y = 'Sample_ID'))

cols_to_keep = c('Sample_ID', 'avg_nfoci')
baseline = baseline_avgfoci[, colnames(baseline_avgfoci) %in% cols_to_keep]
colnames(baseline)[colnames(baseline) == "avg_nfoci"] = "baseline_avg_nfoci"

all_flow_meta = merge(all_flow_meta, baseline, by.x = 'Sample_ID', by.y = 'Sample_ID', all=TRUE)
```

```{r}
## Combine both RIF and flow data
all_RIF_flow = merge(all_RIF_meta, all_flow_meta, by.x = 'Sample_ID', by.y = 'Sample_ID', all=TRUE)
all_RIF_flow = distinct(all_RIF_flow)
```

```{r}
## Clean-up
all_RIF_flow$Run_set_well = all_RIF_flow$Run_set_well.y
all_RIF_flow$Age = all_RIF_flow$Age.y
all_RIF_flow$Gender = all_RIF_flow$Gender.y
all_RIF_flow$BMI = all_RIF_flow$BMI.y
all_RIF_flow$BMI_group = all_RIF_flow$BMI_group.y
all_RIF_flow$CMV = all_RIF_flow$CMV.y
all_RIF_flow$Collection_Date = all_RIF_flow$Collection_Date.y
cols_to_drop = c('Run_set_well.x','Run_set_well.y','Age.x','Age.y','Gender.x', 'Gender.y', 'BMI.x', 'BMI.y','BMI_group.x','BMI_group.y','CMV.x','CMV.y','Collection_Date.x','Collection_Date.y')
all_RIF_flow = all_RIF_flow[, !colnames(all_RIF_flow) %in% cols_to_drop]
```

```{r}
merge_metadata = merge(well_meta, all_RIF_flow, by="Sample_ID")

merge_metadata$Run_set_well = all_RIF_flow$Run_set_well.x
merge_metadata$Age = merge_metadata$Age.x
merge_metadata$Gender = merge_metadata$Gender.x
merge_metadata$BMI = merge_metadata$BMI.x
merge_metadata$BMI_group = merge_metadata$BMI_group.x
merge_metadata$CMV = merge_metadata$CMV.x
merge_metadata$Collection_Date = merge_metadata$Collection_Date.x
cols_to_drop = c('Run_set_well.x','Run_set_well.y','Age.x','Age.y','Gender.x', 'Gender.y', 'BMI.x', 'BMI.y','BMI_group.x','BMI_group.y','CMV.x','CMV.y','Collection_Date.x','Collection_Date.y')
merge_metadata = merge_metadata[, !colnames(merge_metadata) %in% cols_to_drop]

write.csv(merge_metadata,"Data_All_Phenotypes_Raw.csv")

```
