```{r}
require('lattice')
require('ggalt')
require('ggplot2')
require('polynom')
require('corrplot')
require('ggpubr')
require('plyr')
require('reshape2')
require('cowplot')
require('stringr')
require('ggforce')
require('dplyr')
```

```{r}
setwd("/Users/epariset/Desktop/R_Code_RIF") ## Change as necessary: this is the main directory
theme_set(theme_bw(base_size = 12)) ## For prettier graphs
theme_update(plot.title = element_text(hjust = 0.5))
```

```{r}
baseline_plate_nums = c(428, 429, 430, 431, 432, 625, 626, 627, 628, 629, 630)
baseline_plate_count = length(baseline_plate_nums)

```

```{r}
## Read all metadata
subject_meta = read.csv('/Users/epariset/Desktop/R_Code_RIF/Baseline_metadata.csv', sep = ",", header = TRUE)
#lcolnames(subject_meta)[colnames(subject_meta)=="ï..Sample_ID"]<-"Sample_ID"
subject_ids = unique(subject_meta$Sample_ID)
num_subj = length(subject_ids)
```

```{r}
plate_meta = read.csv('/Users/epariset/Desktop/R_Code_RIF/Baseline_plate_metadata.csv', sep = ",", header = TRUE)
plate_ids = unique(plate_meta$Plate_number)
num_plate = length(plate_ids)
```

```{r}
## Read first file
foci_baseline_first = data.frame(Plate = baseline_plate_nums[1], Plate_well = paste(baseline_plate_nums[1], read.table(paste("/Users/epariset/Desktop/Baselines-CD7/average_well_P", baseline_plate_nums[1],'.txt', sep=""), sep="\t", header = TRUE)$Well, sep = "_"), read.table(paste("/Users/epariset/Desktop/Baselines-CD7/average_well_P", baseline_plate_nums[1],'.txt', sep=""), sep="\t", header = TRUE))

baseline_table=foci_baseline_first

```

## Read all the other files and combine them into a single giant file with ALL the plates and ALL the wells
# This is just to read the data

```{r}
for(ii in 2:baseline_plate_count){
  temp_baseline_filename = paste('/Users/epariset/Desktop/Baselines-CD7/average_well_P', baseline_plate_nums[ii],'.txt', sep="")
  temp_baseline_table = data.frame(Plate = baseline_plate_nums[ii], Plate_well = paste(baseline_plate_nums[ii], read.table(paste('/Users/epariset/Desktop/Baselines-CD7/average_well_P', baseline_plate_nums[ii],'.txt', sep=""), sep="\t", header = TRUE)$Well, sep = "_"), read.table(paste('/Users/epariset/Desktop/Baselines-CD7/average_well_P', baseline_plate_nums[ii],'.txt', sep=""), sep="\t", header = TRUE))
  baseline_table = rbind(baseline_table, temp_baseline_table)
}
```



```{r}

  source("Baseline_Graphs.R", echo = TRUE)
  source("Baseline_Data.R", echo=TRUE)

```