---
title: "Comparision High-Throughput vs CD7"
---



```{r}
require('lattice')
require('ggplot2')
require('polynom')
##require('ggpubr')
require('plyr')
require('reshape2')
##require('cowplot')
require('stringr')
##require('ggforce')
require('dplyr')
#install.packages('proj4')
library('proj4')
require('ggalt')
library(IDPmisc)
library(plotly)
require('sva')
library(devtools)
#install_github("vqv/ggbiplot")
library(ggbiplot)
require('rlist')
require('gridExtra')



### Need to run chunk starting line 792 twice :

  # a first time with lines 880, 1550 and 2072 uncommented and lines 882, 1551 and 2073 commented
  # a second time with lines 882, 1551 and 2073 uncommented and lines 880, 1550 and 2072 commented

# Then run the last chunk starting line 2078
```


```{r}
setwd(getwd())

theme_set(theme_bw(base_size = 12)) ## For prettier graphs
theme_update(plot.title = element_text(hjust = 0.5))

### dose en Gy
low_dose_Fe = 0.3 
low_dose_Ar = 0.18 
low_dose_Si = 0.11 
low_dose_Gamma = 0.1

high_dose_Fe = 0.82 
high_dose_Ar = 0.5 
high_dose_Si = 0.29 
high_dose_Gamma = 1
```


```{r}
##################################################################################################
##################################################################################################
############################## Finsam's ComBat modified Function #################################
##################################################################################################
##################################################################################################

sva.class2Model <- function(classes) {
  return(model.matrix(~factor(classes)))
}


modefunc <- function(x) {
  return(as.numeric(names(sort(-table(x)))[1]))
}

mono <- function(lfdr){
  .Call("monotone", as.numeric(lfdr), PACKAGE="sva")
}

edge.lfdr <- function(p, trunc=TRUE, monotone=TRUE, transf=c("probit", "logit"), adj=1.5, eps=10^-8, lambda=0.8, ...) {
  pi0 <- mean(p >= lambda)/(1 - lambda)
  pi0 <- min(pi0, 1)
  
  n <- length(p)
  transf <- match.arg(transf)
  
  if(transf=="probit") {
    p <- pmax(p, eps)
    p <- pmin(p, 1-eps)
    x <- qnorm(p)
    myd <- density(x, adjust=adj)
    mys <- smooth.spline(x=myd$x, y=myd$y)
    y <- predict(mys, x)$y
    lfdr <- pi0*dnorm(x)/y
  }
  
  if(transf=="logit") {
    x <- log((p+eps)/(1-p+eps))
    myd <- density(x, adjust=adj)
    mys <- smooth.spline(x=myd$x, y=myd$y)
    y <- predict(mys, x)$y
    dx <- exp(x) / (1+exp(x))^2
    lfdr <- pi0 * dx/y
  }
  
  if(trunc) {
    lfdr[lfdr > 1] <- 1
  }
  if(monotone) {	
    lfdr <- lfdr[order(p)]
    lfdr <- mono(lfdr)
    lfdr <- lfdr[rank(p)]
  }
  
  return(lfdr)
}



# Trims the data of extra columns, note your array names cannot be named 'X' or start with 'X.'
trim.dat <- function(dat){
  tmp <- strsplit(colnames(dat),'\\.')
  tr <- NULL
  for (i in 1:length(tmp)) {
    tr <- c(tr, tmp[[i]][1] != 'X')
  }
  tr
}

# Following four find empirical hyper-prior values
aprior <- function(gamma.hat) {
  m <- mean(gamma.hat)
  s2 <- var(gamma.hat)
  (2*s2 + m^2) / s2
}

bprior <- function(gamma.hat){
  m <- mean(gamma.hat)
  s2 <- var(gamma.hat)
  (m*s2 + m^3) / s2
}

postmean <- function(g.hat,g.bar,n,d.star,t2){
  (t2*n*g.hat + d.star*g.bar) / (t2*n + d.star)
}

postvar <- function(sum2,n,a,b){
  (.5*sum2 + b) / (n/2 + a - 1)
}

# Inverse gamma distribution density function. (Note: does not do any bounds checking on arguments)
dinvgamma <- function (x, shape, rate = 1/scale, scale = 1) {
  # PDF taken from https://en.wikipedia.org/wiki/Inverse-gamma_distribution
  # Note: alpha = shape, beta = rate
  stopifnot(shape > 0)
  stopifnot(rate > 0)
  ifelse(x <= 0, 0, ((rate ^ shape) / gamma(shape)) * x ^ (-shape - 1) * exp(-rate/x))
}

# Pass in entire data set, the design matrix for the entire data, the batch means, the batch variances, priors (m, t2, a, b), columns of the data  matrix for the batch. Uses the EM to find the parametric batch adjustments

it.sol  <- function(sdat,g.hat,d.hat,g.bar,t2,a,b,conv=.0001){
  n <- rowSums(!is.na(sdat))
  g.old <- g.hat
  d.old <- d.hat
  change <- 1
  count <- 0
  while(change>conv){
    g.new <- postmean(g.hat, g.bar, n, d.old, t2)
    sum2 <- rowSums((sdat - g.new %*% t(rep(1,ncol(sdat))))^2, na.rm=TRUE)
    d.new <- postvar(sum2, n, a, b)
    change <- max(abs(g.new-g.old) / g.old, abs(d.new-d.old) / d.old)
    g.old <- g.new
    d.old <- d.new
    count <- count+1
  }
  ## cat("This batch took", count, "iterations until convergence\n")
  adjust <- rbind(g.new, d.new)
  rownames(adjust) <- c("g.star","d.star")
  adjust
}

## likelihood function used below
L <- function(x,g.hat,d.hat){
  prod(dnorm(x, g.hat, sqrt(d.hat)))
}

## Monte Carlo integration functions
int.eprior <- function(sdat, g.hat, d.hat){
  g.star <- d.star <- NULL
  r <- nrow(sdat)
  for(i in 1:r){
    g <- g.hat[-i]
    d <- d.hat[-i]		
    x <- sdat[i,!is.na(sdat[i,])]
    n <- length(x)
    j <- numeric(n)+1
    dat <- matrix(as.numeric(x), length(g), n, byrow=TRUE)
    resid2 <- (dat-g)^2
    sum2 <- resid2 %*% j
    LH <- 1/(2*pi*d)^(n/2)*exp(-sum2/(2*d))
    LH[LH=="NaN"]=0
    g.star <- c(g.star, sum(g*LH)/sum(LH))
    d.star <- c(d.star, sum(d*LH)/sum(LH))
    ## if(i%%1000==0){cat(i,'\n')}
  }
  adjust <- rbind(g.star,d.star)
  rownames(adjust) <- c("g.star","d.star")
  adjust	
} 

## fits the L/S model in the presence of missing data values

Beta.NA <- function(y,X){
  des <- X[!is.na(y),]
  y1 <- y[!is.na(y)]
  B <- solve(crossprod(des), crossprod(des, y1))
  B
}

################################################################################################
################################################################################################
################################################################################################

ComBat_save <- function(dat, batch, mod = NULL, par.prior = TRUE, prior.plots = FALSE,
                   mean.only = FALSE, ref.batch = NULL, BPPARAM = bpparam("SerialParam")) {
  if(length(dim(batch))>1){
    stop("This version of ComBat only allows one batch variable")
  }  ## to be updated soon!  
  
  ## coerce dat into a matrix
  dat <- as.matrix(dat)
  
  ## find genes with zero variance in any of the batches
  batch <- as.factor(batch)
  zero.rows.lst <- lapply(levels(batch), function(batch_level){
    if(sum(batch==batch_level)>1){
      return(which(apply(dat[, batch==batch_level], 1, function(x){var(x)==0})))
    }else{
      return(which(rep(1,3)==2))
    }
  })
  zero.rows <- Reduce(union, zero.rows.lst)
  keep.rows <- setdiff(1:nrow(dat), zero.rows)
  
  if (length(zero.rows) > 0) {
    cat(sprintf("Found %d genes with uniform expression within a single batch (all zeros); these will not be adjusted for batch.\n", length(zero.rows)))
    # keep a copy of the original data matrix and remove zero var rows
    dat.orig <- dat
    dat <- dat[keep.rows, ]
  }
  
  ## make batch a factor and make a set of indicators for batch
  if(any(table(batch)==1)){mean.only=TRUE}
  if(mean.only==TRUE){
    message("Using the 'mean only' version of ComBat")
  }
  
  batchmod <- model.matrix(~-1+batch)  
  if (!is.null(ref.batch)){
    ## check for reference batch, check value, and make appropriate changes
    if (!(ref.batch%in%levels(batch))) {
      stop("reference level ref.batch is not one of the levels of the batch variable")
    }
    message("Using batch =",ref.batch, "as a reference batch (this batch won't change)")
    ref <- which(levels(as.factor(batch))==ref.batch) # find the reference
    batchmod[,ref] <- 1
  } else {
    ref <- NULL
  }
  message("Found", nlevels(batch), "batches")
  
  ## A few other characteristics on the batches
  n.batch <- nlevels(batch)
  batches <- list()
  for (i in 1:n.batch) {
    batches[[i]] <- which(batch == levels(batch)[i])
  } # list of samples in each batch  
  n.batches <- sapply(batches, length)
  if(any(n.batches==1)){
    mean.only=TRUE
    message("Note: one batch has only one sample, setting mean.only=TRUE")
  }
  n.array <- sum(n.batches)
  ## combine batch variable and covariates
  design <- cbind(batchmod,mod)
  
  ## check for intercept in covariates, and drop if present
  check <- apply(design, 2, function(x) all(x == 1))
  if(!is.null(ref)){
    check[ref] <- FALSE
  } ## except don't throw away the reference batch indicator
  design <- as.matrix(design[,!check])
  
  ## Number of covariates or covariate levels
  message("Adjusting for", ncol(design)-ncol(batchmod), 'covariate(s) or covariate level(s)')
  
  ## Check if the design is confounded
  if(qr(design)$rank < ncol(design)) {
    ## if(ncol(design)<=(n.batch)){stop("Batch variables are redundant! Remove one or more of the batch variables so they are no longer confounded")}
    if(ncol(design)==(n.batch+1)) {
      stop("The covariate is confounded with batch! Remove the covariate and rerun ComBat")
    }
    if(ncol(design)>(n.batch+1)) {
      if((qr(design[,-c(1:n.batch)])$rank<ncol(design[,-c(1:n.batch)]))){
        stop('The covariates are confounded! Please remove one or more of the covariates so the design is not confounded')
      } else {
        stop("At least one covariate is confounded with batch! Please remove confounded covariates and rerun ComBat")
      }
    }
  }
  
  ## Check for missing values
  NAs <- any(is.na(dat))
  if(NAs){
    message(c('Found',sum(is.na(dat)),'Missing Data Values'), sep=' ')}
  ## print(dat[1:2,])
  
  ##Standardize Data across genes
  message('Standardizing Data across genes')
  if (!NAs){
    B.hat <- solve(crossprod(design), tcrossprod(t(design), as.matrix(dat)))
  } else { 
    B.hat <- apply(dat, 1, Beta.NA, design) # FIXME
  }
  
  ## change grand.mean for ref batch
  if(!is.null(ref.batch)){
    grand.mean <- t(B.hat[ref, ])
  } else {
    grand.mean <- crossprod(n.batches/n.array, B.hat[1:n.batch,])
  }
  
  ## change var.pooled for ref batch
  if (!NAs){
    if(!is.null(ref.batch)) {
      ref.dat <- dat[, batches[[ref]]]
      var.pooled <- ((ref.dat-t(design[batches[[ref]], ] %*% B.hat))^2) %*% rep(1/n.batches[ref],n.batches[ref]) # FIXME
    } else {
      var.pooled <- ((dat-t(design %*% B.hat))^2) %*% rep(1/n.array,n.array) # FIXME
    }
  } else {
    if(!is.null(ref.batch)) {
      ref.dat <- dat[, batches[[ref]]]
      var.pooled <- rowVars(ref.dat-t(design[batches[[ref]], ]%*%B.hat), na.rm=TRUE)
    } else {
      var.pooled <- rowVars(dat-t(design %*% B.hat), na.rm=TRUE)
    }
  }
  
  stand.mean <- t(grand.mean) %*% t(rep(1,n.array)) # FIXME
  if(!is.null(design)){
    tmp <- design
    tmp[,c(1:n.batch)] <- 0
    stand.mean <- stand.mean+t(tmp %*% B.hat) #FIXME
  }  
  s.data <- (dat-stand.mean)/(sqrt(var.pooled) %*% t(rep(1,n.array))) # FIXME
  
  ##Get regression batch effect parameters
  message("Fitting L/S model and finding priors")
  batch.design <- design[, 1:n.batch]
  if (!NAs){
    gamma.hat <- solve(crossprod(batch.design), tcrossprod(t(batch.design),
                                                           as.matrix(s.data)))
  } else{
    gamma.hat <- apply(s.data, 1, Beta.NA, batch.design) # FIXME
  }
  delta.hat <- NULL
  for (i in batches){
    if(mean.only==TRUE) {
      delta.hat <- rbind(delta.hat,rep(1,nrow(s.data))) 
    } else {
      delta.hat <- rbind(delta.hat, rowVars(s.data[,i], na.rm=TRUE))
    }
  }
  
  ##Find Priors
  gamma.bar <- rowMeans(gamma.hat)
  t2 <- rowVars(gamma.hat)
  a.prior <- apply(delta.hat, 1, aprior) # FIXME 
  b.prior <- apply(delta.hat, 1, bprior) # FIXME
  
  ## Plot empirical and parametric priors
  
  if (prior.plots && par.prior) {
    old_pars <- par(no.readonly = TRUE)
    on.exit(par(old_pars))
    par(mfrow=c(2,2))
    
    ## Top left
    tmp <- density(gamma.hat[1,])
    plot(tmp,  type='l', main=expression(paste("Density Plot of First Batch ",  hat(gamma))))
    xx <- seq(min(tmp$x), max(tmp$x), length=100)
    lines(xx,dnorm(xx,gamma.bar[1],sqrt(t2[1])), col=2)
    
    ## Top Right
    qqnorm(gamma.hat[1,], main=expression(paste("Normal Q-Q Plot of First Batch ", hat(gamma))))
    qqline(gamma.hat[1,], col=2)
    
    ## Bottom Left
    tmp <- density(delta.hat[1,])
    xx <- seq(min(tmp$x), max(tmp$x), length=100)
    tmp1 <- list(x=xx, y=dinvgamma(xx, a.prior[1], b.prior[1]))
    plot(tmp, typ="l", ylim=c(0, max(tmp$y, tmp1$y)),
         main=expression(paste("Density Plot of First Batch ", hat(delta))))
    lines(tmp1, col=2)
    
    ## Bottom Right
    invgam <- 1/qgamma(1-ppoints(ncol(delta.hat)), a.prior[1], b.prior[1])
    qqplot(invgam, delta.hat[1,],
           main=expression(paste("Inverse Gamma Q-Q Plot of First Batch ", hat(delta))),
           ylab="Sample Quantiles", xlab="Theoretical Quantiles")
    lines(c(0, max(invgam)), c(0, max(invgam)), col=2)
  }
  
  ## Find EB batch adjustments
  
  gamma.star <- delta.star <- matrix(NA, nrow=n.batch, ncol=nrow(s.data))
  if (par.prior) {
    message("Finding parametric adjustments")
    results <- bplapply(1:n.batch, function(i) {
      if (mean.only) {
        gamma.star <- postmean(gamma.hat[i,], gamma.bar[i], 1, 1, t2[i])
        delta.star <- rep(1, nrow(s.data))
      }
      else {
        temp <- it.sol(s.data[, batches[[i]]], gamma.hat[i, ],
                       delta.hat[i, ], gamma.bar[i], t2[i], a.prior[i],
                       b.prior[i])
        gamma.star <- temp[1, ]
        delta.star <- temp[2, ]
      }
      list(gamma.star=gamma.star, delta.star=delta.star)
    }, BPPARAM = BPPARAM)
    for (i in 1:n.batch) {
      gamma.star[i,] <- results[[i]]$gamma.star
      delta.star[i,] <- results[[i]]$delta.star
    }
  }
  else {
    message("Finding nonparametric adjustments")
    results <- bplapply(1:n.batch, function(i) {
      if (mean.only) {
        delta.hat[i, ] = 1
      }
      temp <- int.eprior(as.matrix(s.data[, batches[[i]]]),
                         gamma.hat[i, ], delta.hat[i, ])
      list(gamma.star=temp[1,], delta.star=temp[2,])
    }, BPPARAM = BPPARAM)
    for (i in 1:n.batch) {
      gamma.star[i,] <- results[[i]]$gamma.star
      delta.star[i,] <- results[[i]]$delta.star
    }
  }
  
  if(!is.null(ref.batch)){
    gamma.star[ref,] <- 0  ## set reference batch mean equal to 0
    delta.star[ref,] <- 1  ## set reference batch variance equal to 1
  }
  
  ## Normalize the Data ###
  message("Adjusting the Data\n")
  
  bayesdata <- s.data
  j <- 1
  for (i in batches){
    ## DEBUG LINES
    samples_umrr <- bayesdata[,i]
    sub_umrr <- t(batch.design[i,]%*%gamma.star)
    ##
    bayesdata[,i] <- (bayesdata[,i]-t(batch.design[i,]%*%gamma.star))/(sqrt(delta.star[j,])%*%t(rep(1,n.batches[j]))) # FIXME
    j <- j+1
  }
  
  bayesdata <- (bayesdata*(sqrt(var.pooled)%*%t(rep(1,n.array))))+stand.mean # FIXME
  
  ## Do not change ref batch at all in reference version
  if(!is.null(ref.batch)){
    bayesdata[, batches[[ref]]] <- dat[, batches[[ref]]]
  }
  
  ## put genes with 0 variance in any batch back in data
  if (length(zero.rows) > 0) {
    dat.orig[keep.rows, ] <- bayesdata
    bayesdata <- dat.orig
  }
  
  ## EXTRACT
  gamma.star.out <- gamma.star
  delta.star.out <- delta.star
  colnames(gamma.star.out) <- rownames(s.data)
  colnames(delta.star.out) <- rownames(s.data)
  combat_save_out <- list("data"=bayesdata, "gamma"=gamma.star.out, "delta"=delta.star.out)
  
  # return(bayesdata)
  return(combat_save_out)
}

ComBat_custom <- function(dat, batch, custom.gamma, custom.delta, mod = NULL, par.prior = TRUE, prior.plots = FALSE,
                        mean.only = FALSE, ref.batch = NULL, BPPARAM = bpparam("SerialParam")) {
  if(length(dim(batch))>1){
    stop("This version of ComBat only allows one batch variable")
  }  ## to be updated soon!  
  
  ## coerce dat into a matrix
  dat <- as.matrix(dat)
  
  ## find genes with zero variance in any of the batches
  batch <- as.factor(batch)
  zero.rows.lst <- lapply(levels(batch), function(batch_level){
    if(sum(batch==batch_level)>1){
      return(which(apply(dat[, batch==batch_level], 1, function(x){var(x)==0})))
    }else{
      return(which(rep(1,3)==2))
    }
  })
  zero.rows <- Reduce(union, zero.rows.lst)
  keep.rows <- setdiff(1:nrow(dat), zero.rows)
  
  if (length(zero.rows) > 0) {
    cat(sprintf("Found %d genes with uniform expression within a single batch (all zeros); these will not be adjusted for batch.\n", length(zero.rows)))
    # keep a copy of the original data matrix and remove zero var rows
    dat.orig <- dat
    dat <- dat[keep.rows, ]
  }
  
  ## make batch a factor and make a set of indicators for batch
  if(any(table(batch)==1)){mean.only=TRUE}
  if(mean.only==TRUE){
    message("Using the 'mean only' version of ComBat")
  }
  
  batchmod <- model.matrix(~-1+batch)  
  if (!is.null(ref.batch)){
    ## check for reference batch, check value, and make appropriate changes
    if (!(ref.batch%in%levels(batch))) {
      stop("reference level ref.batch is not one of the levels of the batch variable")
    }
    message("Using batch =",ref.batch, "as a reference batch (this batch won't change)")
    ref <- which(levels(as.factor(batch))==ref.batch) # find the reference
    batchmod[,ref] <- 1
  } else {
    ref <- NULL
  }
  message("Found", nlevels(batch), "batches")
  
  ## A few other characteristics on the batches
  n.batch <- nlevels(batch)
  batches <- list()
  for (i in 1:n.batch) {
    batches[[i]] <- which(batch == levels(batch)[i])
  } # list of samples in each batch  
  n.batches <- sapply(batches, length)
  if(any(n.batches==1)){
    mean.only=TRUE
    message("Note: one batch has only one sample, setting mean.only=TRUE")
  }
  n.array <- sum(n.batches)
  ## combine batch variable and covariates
  design <- cbind(batchmod,mod)
  
  ## check for intercept in covariates, and drop if present
  check <- apply(design, 2, function(x) all(x == 1))
  if(!is.null(ref)){
    check[ref] <- FALSE
  } ## except don't throw away the reference batch indicator
  design <- as.matrix(design[,!check])
  
  ## Number of covariates or covariate levels
  message("Adjusting for", ncol(design)-ncol(batchmod), 'covariate(s) or covariate level(s)')
  
  ## Check if the design is confounded
  if(qr(design)$rank < ncol(design)) {
    ## if(ncol(design)<=(n.batch)){stop("Batch variables are redundant! Remove one or more of the batch variables so they are no longer confounded")}
    if(ncol(design)==(n.batch+1)) {
      stop("The covariate is confounded with batch! Remove the covariate and rerun ComBat")
    }
    if(ncol(design)>(n.batch+1)) {
      if((qr(design[,-c(1:n.batch)])$rank<ncol(design[,-c(1:n.batch)]))){
        stop('The covariates are confounded! Please remove one or more of the covariates so the design is not confounded')
      } else {
        stop("At least one covariate is confounded with batch! Please remove confounded covariates and rerun ComBat")
      }
    }
  }
  
  ## Check for missing values
  NAs <- any(is.na(dat))
  if(NAs){
    message(c('Found',sum(is.na(dat)),'Missing Data Values'), sep=' ')}
  ## print(dat[1:2,])
  
  ##Standardize Data across genes
  message('Standardizing Data across genes')
  if (!NAs){
    B.hat <- solve(crossprod(design), tcrossprod(t(design), as.matrix(dat)))
  } else { 
    B.hat <- apply(dat, 1, Beta.NA, design) # FIXME
  }
  
  ## change grand.mean for ref batch
  if(!is.null(ref.batch)){
    grand.mean <- t(B.hat[ref, ])
  } else {
    grand.mean <- crossprod(n.batches/n.array, B.hat[1:n.batch,])
  }
  
  ## change var.pooled for ref batch
  if (!NAs){
    if(!is.null(ref.batch)) {
      ref.dat <- dat[, batches[[ref]]]
      var.pooled <- ((ref.dat-t(design[batches[[ref]], ] %*% B.hat))^2) %*% rep(1/n.batches[ref],n.batches[ref]) # FIXME
    } else {
      var.pooled <- ((dat-t(design %*% B.hat))^2) %*% rep(1/n.array,n.array) # FIXME
    }
  } else {
    if(!is.null(ref.batch)) {
      ref.dat <- dat[, batches[[ref]]]
      var.pooled <- rowVars(ref.dat-t(design[batches[[ref]], ]%*%B.hat), na.rm=TRUE)
    } else {
      var.pooled <- rowVars(dat-t(design %*% B.hat), na.rm=TRUE)
    }
  }
  
  stand.mean <- t(grand.mean) %*% t(rep(1,n.array)) # FIXME
  if(!is.null(design)){
    tmp <- design
    tmp[,c(1:n.batch)] <- 0
    stand.mean <- stand.mean+t(tmp %*% B.hat) #FIXME
  }  
  s.data <- (dat-stand.mean)/(sqrt(var.pooled) %*% t(rep(1,n.array))) # FIXME
  
  ##Get regression batch effect parameters
  message("Fitting L/S model and finding priors")
  batch.design <- design[, 1:n.batch]
  if (!NAs){
    gamma.hat <- solve(crossprod(batch.design), tcrossprod(t(batch.design),
                                                           as.matrix(s.data)))
  } else{
    gamma.hat <- apply(s.data, 1, Beta.NA, batch.design) # FIXME
  }
  delta.hat <- NULL
  for (i in batches){
    if(mean.only==TRUE) {
      delta.hat <- rbind(delta.hat,rep(1,nrow(s.data))) 
    } else {
      delta.hat <- rbind(delta.hat, rowVars(s.data[,i], na.rm=TRUE))
    }
  }
  
  ##Find Priors
  gamma.bar <- rowMeans(gamma.hat)
  t2 <- rowVars(gamma.hat)
  a.prior <- apply(delta.hat, 1, aprior) # FIXME 
  b.prior <- apply(delta.hat, 1, bprior) # FIXME
  
  ## Plot empirical and parametric priors
  if (prior.plots && par.prior) {
    old_pars <- par(no.readonly = TRUE)
    on.exit(par(old_pars))
    par(mfrow=c(2,2))
    
    ## Top left
    tmp <- density(gamma.hat[1,])
    plot(tmp,  type='l', main=expression(paste("Density Plot of First Batch ",  hat(gamma))))
    xx <- seq(min(tmp$x), max(tmp$x), length=100)
    lines(xx,dnorm(xx,gamma.bar[1],sqrt(t2[1])), col=2)
    
    ## Top Right
    qqnorm(gamma.hat[1,], main=expression(paste("Normal Q-Q Plot of First Batch ", hat(gamma))))
    qqline(gamma.hat[1,], col=2)
    
    ## Bottom Left
    tmp <- density(delta.hat[1,])
    xx <- seq(min(tmp$x), max(tmp$x), length=100)
    tmp1 <- list(x=xx, y=dinvgamma(xx, a.prior[1], b.prior[1]))
    plot(tmp, typ="l", ylim=c(0, max(tmp$y, tmp1$y)),
         main=expression(paste("Density Plot of First Batch ", hat(delta))))
    lines(tmp1, col=2)
    
    ## Bottom Right
    invgam <- 1/qgamma(1-ppoints(ncol(delta.hat)), a.prior[1], b.prior[1])
    qqplot(invgam, delta.hat[1,],
           main=expression(paste("Inverse Gamma Q-Q Plot of First Batch ", hat(delta))),
           ylab="Sample Quantiles", xlab="Theoretical Quantiles")
    lines(c(0, max(invgam)), c(0, max(invgam)), col=2)
  }
  
  ## Find EB batch adjustments
  gamma.star <- delta.star <- matrix(NA, nrow=n.batch, ncol=nrow(s.data))
  if (par.prior) {
    message("Finding parametric adjustments")
    results <- bplapply(1:n.batch, function(i) {
      if (mean.only) {
        gamma.star <- postmean(gamma.hat[i,], gamma.bar[i], 1, 1, t2[i])
        delta.star <- rep(1, nrow(s.data))
      }
      else {
        temp <- it.sol(s.data[, batches[[i]]], gamma.hat[i, ],
                       delta.hat[i, ], gamma.bar[i], t2[i], a.prior[i],
                       b.prior[i])
        gamma.star <- temp[1, ]
        delta.star <- temp[2, ]
      }
      list(gamma.star=gamma.star, delta.star=delta.star)
    }, BPPARAM = BPPARAM)
    for (i in 1:n.batch) {
      gamma.star[i,] <- results[[i]]$gamma.star
      delta.star[i,] <- results[[i]]$delta.star
    }
  }
  else {
    message("Finding nonparametric adjustments")
    results <- bplapply(1:n.batch, function(i) {
      if (mean.only) {
        delta.hat[i, ] = 1
      }
      temp <- int.eprior(as.matrix(s.data[, batches[[i]]]),
                         gamma.hat[i, ], delta.hat[i, ])
      list(gamma.star=temp[1,], delta.star=temp[2,])
    }, BPPARAM = BPPARAM)
    for (i in 1:n.batch) {
      gamma.star[i,] <- results[[i]]$gamma.star
      delta.star[i,] <- results[[i]]$delta.star
    }
  }
  
  if(!is.null(ref.batch)){
    gamma.star[ref,] <- 0  ## set reference batch mean equal to 0
    delta.star[ref,] <- 1  ## set reference batch variance equal to 1
  }
  
  ## Normalize the Data ###
  message("Adjusting the Data\n")
  
  bayesdata <- s.data
  
  
  ## CREATE BLANKS
  ## gamma is additive, delta is multiplicative
  gamma.star.blank <- gamma.star
  colnames(gamma.star.blank) <- rownames(s.data)
  gamma.star.blank[] <- 0
  delta.star.blank <- delta.star
  colnames(delta.star.blank) <- rownames(s.data)
  delta.star.blank[] <- 1
  
  ## Replace matching columns
  # Select indices, omit nans
  gamma_indices1_with_nan <- match(colnames(custom.gamma), colnames(gamma.star.blank))
  gamma_indices1 <- na.omit(gamma_indices1_with_nan)
  gamma_indices2_with_nan <- match(colnames(gamma.star.blank), colnames(custom.gamma)) # GETS NEEDED INDICES TO INDEX FROM CUSTOM
  gamma_indices2 <- na.omit(gamma_indices2_with_nan)
  
  delta_indices1_with_nan <- match(colnames(custom.delta), colnames(delta.star.blank))
  delta_indices1 <- na.omit(delta_indices1_with_nan)
  delta_indices2_with_nan <- match(colnames(delta.star.blank), colnames(custom.delta)) # GETS NEEDED INDICES TO INDEX FROM CUSTOM
  delta_indices2 <- na.omit(delta_indices2_with_nan)
  
  # Replace
  gamma.star.blank[,gamma_indices1] <- custom.gamma[,gamma_indices2]
  delta.star.blank[,delta_indices1] <- custom.delta[,delta_indices2]
  
  j <- 1
  for (i in batches){
    ## DEBUG LINES
    #samples_run <- bayesdata[,i]
    #sub_run <- t(batch.design[i,]%*%gamma.star)
    ##
    bayesdata[,i] <- (bayesdata[,i]-t(batch.design[i,]%*%gamma.star.blank))/(sqrt(delta.star.blank[j,])%*%t(rep(1,n.batches[j]))) # FIXME
    j <- j+1
  }
  
  bayesdata <- (bayesdata*(sqrt(var.pooled)%*%t(rep(1,n.array))))+stand.mean # FIXME
  
  ## Do not change ref batch at all in reference version
  if(!is.null(ref.batch)){
    bayesdata[, batches[[ref]]] <- dat[, batches[[ref]]]
  }
  
  ## put genes with 0 variance in any batch back in data
  if (length(zero.rows) > 0) {
    dat.orig[keep.rows, ] <- bayesdata
    bayesdata <- dat.orig
  }
  
  # combat_save_out <- list("data"=bayesdata, "gamma"=gamma.star, "delta"=delta.star)
  
  return(bayesdata)
  # return(combat_save_out)
}

```




```{r}
##################################################################################################
######################################### Read RIF DATA ##########################################
##################################################################################################


#### Read DNA damage data BNL19A
gamma_plate_nums_19A = c(433, 435, 437, 439, 441, 444, 445, 447, 449, 451, 453, 455, 457, 459, 461, 463, 465, 467, 469, 471, 473, 475, 477,479)
gamma_plate_count_19A = length(gamma_plate_nums_19A)
ar_plate_nums_19A = c(481, 483, 485, 487, 489, 491, 493, 495, 497, 499, 501, 503, 505, 507, 509, 511, 513, 515, 517, 519, 521, 523, 525,527)
ar_plate_count_19A = length(ar_plate_nums_19A)
si_plate_nums_19A = c(577, 579, 581, 583, 585, 587, 589, 591, 593, 595, 597, 599, 601, 603, 605,607, 609, 611, 613,615, 617, 619, 621, 623)
si_plate_count_19A = length(si_plate_nums_19A)
fe_plate_nums_19A = c(529, 531, 533, 535, 537, 539, 541, 543, 545, 547, 549, 551, 553, 555, 557, 559, 561, 563, 565, 567, 569, 571, 573,575)
fe_plate_count_19A = length(fe_plate_nums_19A)
gamma_si_fe_ar_plate_nums_19A = c(gamma_plate_nums_19A, si_plate_nums_19A, fe_plate_nums_19A, ar_plate_nums_19A)
gamma_si_fe_ar_plate_count_19A = length(gamma_si_fe_ar_plate_nums_19A)


#### Read first file
foci_gamma_first_19A = data.frame(Plate = gamma_plate_nums_19A[1], Plate_well = paste(gamma_plate_nums_19A[1], read.table(paste("BNL19A-ProcessedFiles-Threshold3000/average_well_P", gamma_plate_nums_19A[1],'.txt', sep=""), sep="\t", header = TRUE)$Well, sep = "_"), read.table(paste("BNL19A-ProcessedFiles-Threshold3000/average_well_P", gamma_plate_nums_19A[1],'.txt', sep=""), sep="\t", header = TRUE))

gamma_table_19A=foci_gamma_first_19A

foci_si_first_19A = data.frame(Plate = si_plate_nums_19A[1], Plate_well = paste(si_plate_nums_19A[1], read.table(paste("BNL19A-ProcessedFiles-Threshold3000/average_well_P", si_plate_nums_19A[1],'.txt', sep=""), sep="\t", header = TRUE)$Well, sep = "_"), read.table(paste("BNL19A-ProcessedFiles-Threshold3000/average_well_P", si_plate_nums_19A[1],'.txt', sep=""), sep="\t", header = TRUE))

si_table_19A=foci_si_first_19A

foci_ar_first_19A = data.frame(Plate = ar_plate_nums_19A[1], Plate_well = paste(ar_plate_nums_19A[1], read.table(paste("BNL19A-ProcessedFiles-Threshold3000/average_well_P", ar_plate_nums_19A[1],'.txt', sep=""), sep="\t", header = TRUE)$Well, sep = "_"), read.table(paste("BNL19A-ProcessedFiles-Threshold3000/average_well_P", ar_plate_nums_19A[1],'.txt', sep=""), sep="\t", header = TRUE))

ar_table_19A=foci_ar_first_19A

foci_fe_first_19A = data.frame(Plate = fe_plate_nums_19A[1], Plate_well = paste(fe_plate_nums_19A[1], read.table(paste("BNL19A-ProcessedFiles-Threshold3000/average_well_P", fe_plate_nums_19A[1],'.txt', sep=""), sep="\t", header = TRUE)$Well, sep = "_"), read.table(paste("BNL19A-ProcessedFiles-Threshold3000/average_well_P", fe_plate_nums_19A[1],'.txt', sep=""), sep="\t", header = TRUE))

fe_table_19A=foci_fe_first_19A


#### Read all the other files and combine them into a single giant file with ALL the plates and ALL the wells
for(ii in 2:gamma_plate_count_19A){
  temp_gamma_filename = paste('BNL19A-ProcessedFiles-Threshold3000/average_well_P', gamma_plate_nums_19A[ii],'.txt', sep="")
  temp_gamma_table = data.frame(Plate = gamma_plate_nums_19A[ii], Plate_well = paste(gamma_plate_nums_19A[ii], read.table(paste('BNL19A-ProcessedFiles-Threshold3000/average_well_P', gamma_plate_nums_19A[ii],'.txt', sep=""), sep="\t", header = TRUE)$Well, sep = "_"), read.table(paste('BNL19A-ProcessedFiles-Threshold3000/average_well_P', gamma_plate_nums_19A[ii],'.txt', sep=""), sep="\t", header = TRUE))
  gamma_table_19A = rbind(gamma_table_19A, temp_gamma_table)
}

for(ii in 2:si_plate_count_19A){
  temp_si_filename = paste('BNL19A-ProcessedFiles-Threshold3000/average_well_P', si_plate_nums_19A[ii],'.txt', sep="")
  temp_si_table = data.frame(Plate = si_plate_nums_19A[ii], Plate_well = paste(si_plate_nums_19A[ii], read.table(paste('BNL19A-ProcessedFiles-Threshold3000/average_well_P', si_plate_nums_19A[ii],'.txt', sep=""), sep="\t", header = TRUE)$Well, sep = "_"), read.table(paste('BNL19A-ProcessedFiles-Threshold3000/average_well_P', si_plate_nums_19A[ii],'.txt', sep=""), sep="\t", header = TRUE))
  si_table_19A = rbind(si_table_19A, temp_si_table)
}

for(ii in 2:ar_plate_count_19A){
  temp_ar_filename = paste('BNL19A-ProcessedFiles-Threshold3000/average_well_P', ar_plate_nums_19A[ii],'.txt', sep="")
  temp_ar_table = data.frame(Plate = ar_plate_nums_19A[ii], Plate_well = paste(ar_plate_nums_19A[ii], read.table(paste('BNL19A-ProcessedFiles-Threshold3000/average_well_P', ar_plate_nums_19A[ii],'.txt', sep=""), sep="\t", header = TRUE)$Well, sep = "_"), read.table(paste('BNL19A-ProcessedFiles-Threshold3000/average_well_P', ar_plate_nums_19A[ii],'.txt', sep=""), sep="\t", header = TRUE))
  ar_table_19A = rbind(ar_table_19A, temp_ar_table)
  }

for(ii in 2:fe_plate_count_19A){
  temp_fe_filename = paste('BNL19A-ProcessedFiles-Threshold3000/average_well_P', fe_plate_nums_19A[ii],'.txt', sep="")
  temp_fe_table = data.frame(Plate = fe_plate_nums_19A[ii], Plate_well = paste(fe_plate_nums_19A[ii], read.table(paste('BNL19A-ProcessedFiles-Threshold3000/average_well_P', fe_plate_nums_19A[ii],'.txt', sep=""), sep="\t", header = TRUE)$Well, sep = "_"), read.table(paste('BNL19A-ProcessedFiles-Threshold3000/average_well_P', fe_plate_nums_19A[ii],'.txt', sep=""), sep="\t", header = TRUE))
  fe_table_19A = rbind(fe_table_19A, temp_fe_table)
  }


#### Read DNA damage data BNL18B
ar_plate_nums_18B = c(381,382,383,386,387,390,391,394,395,396,399,400,402)
ar_plate_count_18B = length(ar_plate_nums_18B)
gamma_plate_nums_18B = c(637, 645, 654,653)
gamma_plate_count_18B = length(gamma_plate_nums_18B)
si_plate_nums_18B = c(333,337,341,345,349,353,342,338,347,346,350)  
si_plate_count_18B = length(si_plate_nums_18B)
fe_plate_nums_18B = c(355,356,357,358,359,360,361,362,363,364,365,366,367,368,369,370,372,373,374,375,376,377,378)
fe_plate_count_18B = length(fe_plate_nums_18B)
fe_ar_plate_nums_18B = c(fe_plate_nums_18B, ar_plate_nums_18B)
fe_ar_plate_count_18B = length(fe_ar_plate_nums_18B)

#### Read first file
foci_ar_first_18B = data.frame(Plate = ar_plate_nums_18B[1], Plate_well = paste(ar_plate_nums_18B[1], read.table(paste("BNL18B-ProcessedFile/Ar-BNL_18B-reimaged/average_well_P", ar_plate_nums_18B[1],'.txt', sep=""), sep="\t", header = TRUE)$Well, sep = "_"), read.table(paste("BNL18B-ProcessedFile/Ar-BNL_18B-reimaged/average_well_P", ar_plate_nums_18B[1],'.txt', sep=""), sep="\t", header = TRUE))

ar_table_18B=foci_ar_first_18B


### To comment /uncomment depending on HT or CD7
foci_gamma_first_18B = data.frame(Plate = gamma_plate_nums_18B[1], Plate_well = paste(gamma_plate_nums_18B[1], read.table(paste("BNL18B-ProcessedFile/Gamma-BNL_18B-reimaged_HT/average_well_P", gamma_plate_nums_18B[1],'.txt', sep=""), sep="\t", header = TRUE)$Well, sep = "_"), read.table(paste("BNL18B-ProcessedFile/Gamma-BNL_18B-reimaged_HT/average_well_P", gamma_plate_nums_18B[1],'.txt', sep=""), sep="\t", header = TRUE))

#foci_gamma_first_18B = data.frame(Plate = gamma_plate_nums_18B[1], Plate_well = paste(gamma_plate_nums_18B[1], read.table(paste("BNL18B-ProcessedFile/Gamma-BNL_18B-reimaged_CD7/average_well_P", gamma_plate_nums_18B[1],'.txt', sep=""), sep="\t", header = TRUE)$Well, sep = "_"), read.table(paste("BNL18B-ProcessedFile/Gamma-BNL_18B-reimaged_CD7/average_well_P", gamma_plate_nums_18B[1],'.txt', sep=""), sep="\t", header = TRUE))
gamma_table_18B=foci_gamma_first_18B

## Add the latest plates imaged in the file 18B reiamged (plates nb: P342, P338, P347, P346, P350 )
foci_si_first_18B = data.frame(Plate = si_plate_nums_18B[1], Plate_well = paste(si_plate_nums_18B[1], read.table(paste("BNL18B-ProcessedFile/Si-BNL_18B-reimaged/average_well_P", si_plate_nums_18B[1],'.txt', sep=""), sep="\t", header = TRUE)$Well, sep = "_"), read.table(paste("BNL18B-ProcessedFile/Si-BNL_18B-reimaged/average_well_P", si_plate_nums_18B[1],'.txt', sep=""), sep="\t", header = TRUE))

si_table_18B=foci_si_first_18B

foci_fe_first_18B = data.frame(Plate = fe_plate_nums_18B[1], Plate_well = paste(fe_plate_nums_18B[1], read.table(paste("BNL18B-ProcessedFile/Fe-BNL_18B-reprocessed/average_well_P", fe_plate_nums_18B[1],'.txt', sep=""), sep="\t", header = TRUE)$Well, sep = "_"), read.table(paste("BNL18B-ProcessedFile/Fe-BNL_18B-reprocessed/average_well_P", fe_plate_nums_18B[1],'.txt', sep=""), sep="\t", header = TRUE))

fe_table_18B=foci_fe_first_18B

#### Read all the other files and combine them into a single giant file with ALL the plates and ALL the wells
for(ii in 2:ar_plate_count_18B){
  temp_ar_filename = paste('BNL18B-ProcessedFile/Ar-BNL_18B-reimaged/average_well_P', ar_plate_nums_18B[ii],'.txt', sep="")
  temp_ar_table = data.frame(Plate = ar_plate_nums_18B[ii], Plate_well = paste(ar_plate_nums_18B[ii], read.table(paste('BNL18B-ProcessedFile/Ar-BNL_18B-reimaged/average_well_P', ar_plate_nums_18B[ii],'.txt', sep=""), sep="\t", header = TRUE)$Well, sep = "_"), read.table(paste('BNL18B-ProcessedFile/Ar-BNL_18B-reimaged/average_well_P', ar_plate_nums_18B[ii],'.txt', sep=""), sep="\t", header = TRUE))
  ar_table_18B = rbind(ar_table_18B, temp_ar_table)
  }

for(ii in 2:si_plate_count_18B){
  temp_si_filename = paste('BNL18B-ProcessedFile/Si-BNL_18B-reimaged/average_well_P', si_plate_nums_18B[ii],'.txt', sep="")
  temp_si_table = data.frame(Plate = si_plate_nums_18B[ii], Plate_well = paste(si_plate_nums_18B[ii], read.table(paste('BNL18B-ProcessedFile/Si-BNL_18B-reimaged/average_well_P', si_plate_nums_18B[ii],'.txt', sep=""), sep="\t", header = TRUE)$Well, sep = "_"), read.table(paste('BNL18B-ProcessedFile/Si-BNL_18B-reimaged/average_well_P', si_plate_nums_18B[ii],'.txt', sep=""), sep="\t", header = TRUE))
  si_table_18B = rbind(si_table_18B, temp_si_table)
  }

for(ii in 2:fe_plate_count_18B){
  temp_fe_filename = paste('BNL18B-ProcessedFile/Fe-BNL_18B-reprocessed/average_well_P', fe_plate_nums_18B[ii],'.txt', sep="")
  temp_fe_table = data.frame(Plate = fe_plate_nums_18B[ii], Plate_well = paste(fe_plate_nums_18B[ii], read.table(paste('BNL18B-ProcessedFile/Fe-BNL_18B-reprocessed/average_well_P', fe_plate_nums_18B[ii],'.txt', sep=""), sep="\t", header = TRUE)$Well, sep = "_"), read.table(paste('BNL18B-ProcessedFile/Fe-BNL_18B-reprocessed/average_well_P', fe_plate_nums_18B[ii],'.txt', sep=""), sep="\t", header = TRUE))
  fe_table_18B = rbind(fe_table_18B, temp_fe_table)
  }

for(ii in 2:gamma_plate_count_18B){
  temp_gamma_filename = paste("BNL18B-ProcessedFile/Gamma-BNL_18B-reimaged_HT/average_well_P", gamma_plate_nums_18B[ii],'.txt', sep="")
  temp_gamma_table = data.frame(Plate = gamma_plate_nums_18B[ii], Plate_well = paste(gamma_plate_nums_18B[ii], read.table(paste("BNL18B-ProcessedFile/Gamma-BNL_18B-reimaged_HT/average_well_P", gamma_plate_nums_18B[ii],'.txt', sep=""), sep="\t", header = TRUE)$Well, sep = "_"), read.table(paste("BNL18B-ProcessedFile/Gamma-BNL_18B-reimaged_HT/average_well_P", gamma_plate_nums_18B[ii],'.txt', sep=""), sep="\t", header = TRUE))
  gamma_table_18B = rbind(gamma_table_18B, temp_gamma_table)
}

#### We combine 18B and 19A data
ar_table = rbind(ar_table_18B, ar_table_19A)
fe_table = rbind(fe_table_18B, fe_table_19A)
si_table = rbind(si_table_18B, si_table_19A)
gamma_table = rbind(gamma_table_18B, gamma_table_19A)


#### add duplicate info
Plate_Duplicate <- read.csv('Plate_Duplicate.csv', header = TRUE, sep = ";", quote = "\"", dec = ".")
Plate_Duplicate$Run=NULL
ar_table=merge(ar_table, Plate_Duplicate, by.x="Plate", by.y="Plate_number", all.x = TRUE)
fe_table=merge(fe_table, Plate_Duplicate, by.x="Plate", by.y="Plate_number", all.x = TRUE)
si_table=merge(si_table, Plate_Duplicate, by.x="Plate", by.y="Plate_number", all.x = TRUE)
gamma_table=merge(gamma_table, Plate_Duplicate, by.x="Plate", by.y="Plate_number", all.x = TRUE)



#### Now we will add plate metadata
plate_meta = read.csv('Plate_metadata_VF.csv', sep = ";", header = TRUE)
fe_table_w_plate_meta = merge(fe_table, plate_meta, by.x = 'Plate', by.y = 'Plate_number', all.x = TRUE, all.y = FALSE)
ar_table_w_plate_meta = merge(ar_table, plate_meta, by.x = 'Plate', by.y = 'Plate_number', all.x = TRUE, all.y = FALSE)
si_table_w_plate_meta = merge(si_table, plate_meta, by.x = 'Plate', by.y = 'Plate_number', all.x = TRUE, all.y = FALSE)
gamma_table_w_plate_meta = merge(gamma_table, plate_meta, by.x = 'Plate', by.y = 'Plate_number', all.x = TRUE, all.y = FALSE)

## Wells are different based on sample sets, so we need to make an extra column for Set_Well, and then add well metadata based on it.
fe_table_w_plate_meta$Run_set_well = paste(fe_table_w_plate_meta$Run, fe_table_w_plate_meta$Sample_sets, fe_table_w_plate_meta$Well, sep = "_")
ar_table_w_plate_meta$Run_set_well = paste(ar_table_w_plate_meta$Run, ar_table_w_plate_meta$Sample_sets, ar_table_w_plate_meta$Well, sep = "_")
si_table_w_plate_meta$Run_set_well = paste(si_table_w_plate_meta$Run, si_table_w_plate_meta$Sample_sets, si_table_w_plate_meta$Well, sep = "_")
gamma_table_w_plate_meta$Run_set_well = paste(gamma_table_w_plate_meta$Run, gamma_table_w_plate_meta$Sample_sets, gamma_table_w_plate_meta$Well, sep = "_")

## create column run_set 
fe_table_w_plate_meta$Run_set = paste(fe_table_w_plate_meta$Run, fe_table_w_plate_meta$Sample_sets, sep = "_")
ar_table_w_plate_meta$Run_set = paste(ar_table_w_plate_meta$Run, ar_table_w_plate_meta$Sample_sets, sep = "_")
si_table_w_plate_meta$Run_set = paste(si_table_w_plate_meta$Run, si_table_w_plate_meta$Sample_sets, sep = "_")
gamma_table_w_plate_meta$Run_set = paste(gamma_table_w_plate_meta$Run, gamma_table_w_plate_meta$Sample_sets, sep = "_")

# For Gamma we rename 19C_set3 and 19C_Set4 as respectively 18B_Set1 and 18B_Set2 (since they are the same subjects: easier for the upcoming analyses)
gamma_table_w_plate_meta$Run_set[gamma_table_w_plate_meta$Run_set == "Run_19C_Set_3"] <- "Run_18B_Set_1"
gamma_table_w_plate_meta$Run_set[gamma_table_w_plate_meta$Run_set == "Run_19C_Set_4"] <- "Run_18B_Set_2"

#### Set low bar. This is arbitrary! We will ask for at least 50 imaged nuclei per well to consider that well. 
low_bar = 50
fe_filt = fe_table_w_plate_meta[fe_table_w_plate_meta$num_nuc > (low_bar-1),]
ar_filt = ar_table_w_plate_meta[ar_table_w_plate_meta$num_nuc > (low_bar-1),]
si_filt = si_table_w_plate_meta[si_table_w_plate_meta$num_nuc > (low_bar-1),]
gamma_filt = gamma_table_w_plate_meta[gamma_table_w_plate_meta$num_nuc > (low_bar-1),]

#### Truncate dataframe to only include the columns of interest
col_trunc = c("Run_set_well", "avg_nfoci", "avg_foci_no_outl", "Dose_Fluence", "Timepoint", "Duplicate", 'Run_set', 'Staining_date','Plate')
fe_trunc = fe_filt[,colnames(fe_filt) %in% col_trunc]

col_trunc = c("Run_set_well", "avg_nfoci", "avg_foci_no_outl", "Dose_Fluence", "Timepoint", "Duplicate", 'Run_set', 'Staining_date','Plate')
ar_trunc = ar_filt[,colnames(ar_filt) %in% col_trunc]

col_trunc = c("Run_set_well", "avg_nfoci", "avg_foci_no_outl", "Dose_Fluence", "Timepoint", "Duplicate", 'Run_set', 'Staining_date','Plate')
si_trunc = si_filt[,colnames(si_filt) %in% col_trunc]

col_trunc = c("Run_set_well", "avg_nfoci", "avg_foci_no_outl", "Dose_Fluence", "Timepoint", "Duplicate", 'Run_set', 'Staining_date','Plate')
gamma_trunc = gamma_filt[,colnames(gamma_filt) %in% col_trunc]


#### Now we combine all ions in a single matrix

## For Fe:
fe_reshaped_1 <- dcast(fe_trunc, Run_set_well + Plate + Duplicate + Staining_date + Run_set + Timepoint ~ Dose_Fluence, value.var = c('avg_nfoci'))
colnames(fe_reshaped_1)[colnames(fe_reshaped_1) == "0"] = "avg_nfoci_0"
colnames(fe_reshaped_1)[colnames(fe_reshaped_1) == "1.1"] = "avg_nfoci_low_dose"
colnames(fe_reshaped_1)[colnames(fe_reshaped_1) == "3"] = "avg_nfoci_high_dose"

fe_reshaped_2 <- dcast(fe_trunc, Run_set_well+ Plate + Duplicate + Staining_date + Run_set + Timepoint ~ Dose_Fluence, value.var = c('avg_foci_no_outl'))
colnames(fe_reshaped_2)[colnames(fe_reshaped_2) == "0"] = "avg_foci_no_outl_0"
colnames(fe_reshaped_2)[colnames(fe_reshaped_2) == "1.1"] = "avg_foci_no_outl_low_dose"
colnames(fe_reshaped_2)[colnames(fe_reshaped_2) == "3"] = "avg_foci_no_outl_high_dose"
 
fe_reshaped = full_join(fe_reshaped_1, fe_reshaped_2, by=c("Run_set_well", "Duplicate", "Staining_date", "Run_set", "Timepoint", "Plate"))

## For Ar:
ar_reshaped_1 <- dcast(ar_trunc, Run_set_well+ Plate + Duplicate + Staining_date + Run_set + Timepoint ~ Dose_Fluence, value.var = c('avg_nfoci'))
colnames(ar_reshaped_1)[colnames(ar_reshaped_1) == "0"] = "avg_nfoci_0"
colnames(ar_reshaped_1)[colnames(ar_reshaped_1) == "1.1"] = "avg_nfoci_low_dose"
colnames(ar_reshaped_1)[colnames(ar_reshaped_1) == "3"] = "avg_nfoci_high_dose"

ar_reshaped_2 <- dcast(ar_trunc, Run_set_well+ Plate + Duplicate + Staining_date + Run_set + Timepoint ~ Dose_Fluence, value.var = c('avg_foci_no_outl'))
colnames(ar_reshaped_2)[colnames(ar_reshaped_2) == "0"] = "avg_foci_no_outl_0"
colnames(ar_reshaped_2)[colnames(ar_reshaped_2) == "1.1"] = "avg_foci_no_outl_low_dose"
colnames(ar_reshaped_2)[colnames(ar_reshaped_2) == "3"] = "avg_foci_no_outl_high_dose"
 
ar_reshaped = full_join(ar_reshaped_1, ar_reshaped_2, by=c("Run_set_well", "Duplicate", "Staining_date", "Run_set", "Timepoint", "Plate"))

## For Si:
si_reshaped_1 <- dcast(si_trunc, Run_set_well + Plate + Duplicate + Staining_date + Run_set + Timepoint ~ Dose_Fluence, value.var = c('avg_nfoci'))
colnames(si_reshaped_1)[colnames(si_reshaped_1) == "0"] = "avg_nfoci_0"
colnames(si_reshaped_1)[colnames(si_reshaped_1) == "1.1"] = "avg_nfoci_low_dose"
colnames(si_reshaped_1)[colnames(si_reshaped_1) == "3"] = "avg_nfoci_high_dose"

si_reshaped_2 <- dcast(si_trunc, Run_set_well + Plate + Duplicate + Staining_date + Run_set + Timepoint ~ Dose_Fluence, value.var = c('avg_foci_no_outl'))
colnames(si_reshaped_2)[colnames(si_reshaped_2) == "0"] = "avg_foci_no_outl_0"
colnames(si_reshaped_2)[colnames(si_reshaped_2) == "1.1"] = "avg_foci_no_outl_low_dose"
colnames(si_reshaped_2)[colnames(si_reshaped_2) == "3"] = "avg_foci_no_outl_high_dose"
 
si_reshaped = full_join(si_reshaped_1, si_reshaped_2, by=c("Run_set_well", "Duplicate", "Staining_date", "Run_set", "Timepoint", "Plate"))

## For Gamma:
dose= gamma_trunc$Dose_Fluence
dose=unique(dose)
print(dose)
gamma_reshaped_1 <- dcast(gamma_trunc, Run_set_well + Plate + Duplicate + Staining_date + Run_set + Timepoint ~ Dose_Fluence, value.var = c('avg_nfoci'))
colnames(gamma_reshaped_1)[colnames(gamma_reshaped_1) == "0"] = "avg_nfoci_0"
colnames(gamma_reshaped_1)[colnames(gamma_reshaped_1) == "0.1"] = "avg_nfoci_low_dose"
colnames(gamma_reshaped_1)[colnames(gamma_reshaped_1) == "1"] = "avg_nfoci_high_dose"

gamma_reshaped_2 <- dcast(gamma_trunc, Run_set_well + Plate + Duplicate + Staining_date + Run_set + Timepoint ~ Dose_Fluence, value.var = c('avg_foci_no_outl'))
colnames(gamma_reshaped_2)[colnames(gamma_reshaped_2) == "0"] = "avg_foci_no_outl_0"
colnames(gamma_reshaped_2)[colnames(gamma_reshaped_2) == "0.1"] = "avg_foci_no_outl_low_dose"
colnames(gamma_reshaped_2)[colnames(gamma_reshaped_2) == "1"] = "avg_foci_no_outl_high_dose"
 
gamma_reshaped = full_join(gamma_reshaped_1, gamma_reshaped_2, by=c("Run_set_well", "Duplicate", "Staining_date", "Run_set", "Timepoint", "Plate"))

#### Add info radiation type + Combine in one table 
fe_reshaped$Radiation_type = "Fe"
ar_reshaped$Radiation_type = "Ar"
si_reshaped$Radiation_type = "Si"
gamma_reshaped$Radiation_type = "Gamma"

all_RIF=bind_rows(fe_reshaped, ar_reshaped)
all_RIF=bind_rows(all_RIF, si_reshaped)
all_RIF=bind_rows(all_RIF, gamma_reshaped)


##### Now we add well metadata
well_meta = read.csv('Well_metadata.csv', sep = ",", header = TRUE)
all_RIF_Raw = merge(all_RIF, well_meta, by.x = 'Run_set_well', by.y = 'Run_set_well', all.x = TRUE)

Subject_metadata_save=all_RIF_Raw[,grepl("Sample_ID|Age|Gender|BMI", colnames(all_RIF_Raw))]

### Correction using Finsam's function : by radiation within each Run_Set
#### we add the Batch numerotation 
Raw_pc = all_RIF_Raw 
Raw_pc$Run_set_well=NULL

Run_set_batch <- read.csv('Run_set_batch.csv', header = TRUE, sep = ";", quote = "\"", dec = ".")

Raw_pc=merge(Raw_pc, Run_set_batch, by="Run_set",all.x = TRUE)
Raw_pc$CMV=NULL
Raw_pcX=NULL

colnames(Raw_pc)[colnames(Raw_pc)=="Batch"] = "Run_set_batch"

Raw_pc_metadata = Raw_pc[,grepl("Sample_ID|Age|Run|BMI",colnames(Raw_pc))]

## Add column radiation_batch 
Raw_pc$Radiation_Batch= Raw_pc$Radiation_type
Raw_pc$Radiation_Batch[Raw_pc$Radiation_Batch=="Fe"] <- 1
Raw_pc$Radiation_Batch[Raw_pc$Radiation_Batch=="Ar"] <- 2
Raw_pc$Radiation_Batch[Raw_pc$Radiation_Batch=="Si"] <- 3
Raw_pc$Radiation_Batch[Raw_pc$Radiation_Batch=="Gamma"] <- 4

metadata_save = Raw_pc[,grep("Sample_ID|Run_set|Duplicate|Staining_date|Timepoint|Radiation_type|Radiation_Batch|Age|BMI|Gender",colnames(Raw_pc))]


# To know how many "Run and set" values we have 
Run_set_list = Raw_pc[, grepl("Run", colnames(Raw_pc))]
Run_set_list=unique(Run_set_list)
print(Run_set_list)


## In this case we have 6 different "Run and set" values, when additional radiation responses will be added need to add lines for respective Run_Set new values 
Run_set_1 = Raw_pc %>% filter(Raw_pc$Run_set_batch == 1)
Run_set_2 = Raw_pc %>% filter(Raw_pc$Run_set_batch == 2)
Run_set_3 = Raw_pc %>% filter(Raw_pc$Run_set_batch == 3)
Run_set_4 = Raw_pc %>% filter(Raw_pc$Run_set_batch == 4)
Run_set_5 = Raw_pc %>% filter(Raw_pc$Run_set_batch == 5)
Run_set_6 = Raw_pc %>% filter(Raw_pc$Run_set_batch == 6)

###### for each run and set value we apply Finsam's function with radiation as a batch effect variable 
##### Run_set_1
metadata_save_1=Run_set_1[,grep("Sample_ID|Run|Duplicate|Staining|Radiation|Timepoint|Age|BMI|Gender",colnames(Run_set_1))]
metadata=Run_set_1[,grep("Sample_ID|Timepoint|Age|BMI|Gender",colnames(Run_set_1))]
metadata$BMI_group=NULL
edata_control=Run_set_1[,grep("avg_nfoci_0|avg_foci_no_outl_0",colnames(Run_set_1))]
edata_control=t(edata_control)
modcombat = model.matrix(~1, data= metadata) 
Batch_C= Run_set_1$Radiation_Batch
## Run Finsam's function
Modified_ComBat = ComBat_save(dat=edata_control, batch=Batch_C, mod=modcombat, par.prior=TRUE, prior.plots=FALSE)
#
Run_Set_1_Corrected_Controls = Modified_ComBat$data
Run_Set_1_Corrected_Controls=t(Run_Set_1_Corrected_Controls)
Run_Set_1_Corrected_Controls=cbind(Run_Set_1_Corrected_Controls, metadata_save_1)
#
Gamma_factor_Run_set_1= Modified_ComBat$gamma
Delta_factor_Run_set_1= Modified_ComBat$delta

##### Run_set_2
metadata_save_2=Run_set_2[,grep("Sample_ID|Run|Duplicate|Staining|Radiation|Timepoint|Age|BMI|Gender",colnames(Run_set_2))]
metadata=Run_set_2[,grep("Sample_ID|Timepoint|Age|BMI|Gender",colnames(Run_set_2))]
metadata$BMI_group=NULL
edata_control=Run_set_2[,grep("avg_nfoci_0|avg_foci_no_outl_0",colnames(Run_set_2))]
edata_control=t(edata_control)
modcombat = model.matrix(~1, data= metadata) 
Batch_C= Run_set_2$Radiation_Batch
## Run Finsam's function
Modified_ComBat = ComBat_save(dat=edata_control, batch=Batch_C, mod=modcombat, par.prior=TRUE, prior.plots=FALSE)
#
Run_Set_2_Corrected_Controls = Modified_ComBat$data
Run_Set_2_Corrected_Controls=t(Run_Set_2_Corrected_Controls)
Run_Set_2_Corrected_Controls=cbind(Run_Set_2_Corrected_Controls, metadata_save_2)
#
Gamma_factor_Run_set_2= Modified_ComBat$gamma
Delta_factor_Run_set_2= Modified_ComBat$delta

##### Run_set_3
metadata_save_3=Run_set_3[,grep("Sample_ID|Run|Duplicate|Staining|Radiation|Timepoint|Age|BMI|Gender",colnames(Run_set_3))]
metadata=Run_set_3[,grep("Sample_ID|Timepoint|Age|BMI|Gender",colnames(Run_set_3))]
metadata$BMI_group=NULL
edata_control=Run_set_3[,grep("avg_nfoci_0|avg_foci_no_outl_0",colnames(Run_set_3))]
edata_control=t(edata_control)
modcombat = model.matrix(~1, data= metadata) 
Batch_C= Run_set_3$Radiation_Batch
## Run Finsam's function
Modified_ComBat = ComBat_save(dat=edata_control, batch=Batch_C, mod=modcombat, par.prior=TRUE, prior.plots=FALSE)
#
Run_Set_3_Corrected_Controls = Modified_ComBat$data
Run_Set_3_Corrected_Controls=t(Run_Set_3_Corrected_Controls)
Run_Set_3_Corrected_Controls=cbind(Run_Set_3_Corrected_Controls, metadata_save_3)
#
Gamma_factor_Run_set_3= Modified_ComBat$gamma
Delta_factor_Run_set_3= Modified_ComBat$delta

##### Run_set_4
metadata_save_4=Run_set_4[,grep("Sample_ID|Run|Duplicate|Staining|Radiation|Timepoint|Age|BMI|Gender",colnames(Run_set_4))]
metadata=Run_set_4[,grep("Sample_ID|Timepoint|Age|BMI|Gender",colnames(Run_set_4))]
metadata$BMI_group=NULL
edata_control=Run_set_4[,grep("avg_nfoci_0|avg_foci_no_outl_0",colnames(Run_set_4))]
edata_control=t(edata_control)
modcombat = model.matrix(~1, data= metadata) 
Batch_C= Run_set_4$Radiation_Batch
## Run Finsam's function
Modified_ComBat = ComBat_save(dat=edata_control, batch=Batch_C, mod=modcombat, par.prior=TRUE, prior.plots=FALSE)
#
Run_Set_4_Corrected_Controls = Modified_ComBat$data
Run_Set_4_Corrected_Controls=t(Run_Set_4_Corrected_Controls)
Run_Set_4_Corrected_Controls=cbind(Run_Set_4_Corrected_Controls, metadata_save_4)
#
Gamma_factor_Run_set_4= Modified_ComBat$gamma
Delta_factor_Run_set_4= Modified_ComBat$delta

##### Run_set_5
metadata_save_5=Run_set_5[,grep("Sample_ID|Run|Duplicate|Staining|Radiation|Timepoint|Age|BMI|Gender",colnames(Run_set_5))]
metadata=Run_set_5[,grep("Sample_ID|Timepoint|Age|BMI|Gender",colnames(Run_set_5))]
metadata$BMI_group=NULL
edata_control=Run_set_5[,grep("avg_nfoci_0|avg_foci_no_outl_0",colnames(Run_set_5))]
edata_control=t(edata_control)
modcombat = model.matrix(~1, data= metadata) 
Batch_C= Run_set_5$Radiation_Batch
## Run Finsam's function
Modified_ComBat = ComBat_save(dat=edata_control, batch=Batch_C, mod=modcombat, par.prior=TRUE, prior.plots=FALSE)
#
Run_Set_5_Corrected_Controls = Modified_ComBat$data
Run_Set_5_Corrected_Controls=t(Run_Set_5_Corrected_Controls)
Run_Set_5_Corrected_Controls=cbind(Run_Set_5_Corrected_Controls, metadata_save_5)
#
Gamma_factor_Run_set_5= Modified_ComBat$gamma
Delta_factor_Run_set_5= Modified_ComBat$delta

##### Run_set_6
metadata_save_6=Run_set_6[,grep("Sample_ID|Run|Duplicate|Staining|Radiation|Timepoint|Age|BMI|Gender",colnames(Run_set_6))]
metadata=Run_set_6[,grep("Sample_ID|Timepoint|Age|BMI|Gender",colnames(Run_set_6))]
metadata$BMI_group=NULL
edata_control=Run_set_6[,grep("avg_nfoci_0|avg_foci_no_outl_0",colnames(Run_set_6))]
edata_control=t(edata_control)
modcombat = model.matrix(~1, data= metadata) 
Batch_C= Run_set_6$Radiation_Batch
## Run Finsam's function
Modified_ComBat = ComBat_save(dat=edata_control, batch=Batch_C, mod=modcombat, par.prior=TRUE, prior.plots=FALSE)
#
Run_Set_6_Corrected_Controls = Modified_ComBat$data
Run_Set_6_Corrected_Controls=t(Run_Set_6_Corrected_Controls)
Run_Set_6_Corrected_Controls=cbind(Run_Set_6_Corrected_Controls, metadata_save_6)
#
Gamma_factor_Run_set_6= Modified_ComBat$gamma
Delta_factor_Run_set_6= Modified_ComBat$delta

######### regroup corrected controls 
Corrected_controls= bind_rows(Run_Set_1_Corrected_Controls, Run_Set_2_Corrected_Controls,
                              Run_Set_3_Corrected_Controls,Run_Set_4_Corrected_Controls,
                              Run_Set_5_Corrected_Controls,Run_Set_6_Corrected_Controls)
Corrected_controls$Rad_dose_Gy = 0
Corrected_controls$Run_set_batch=NULL
Corrected_controls$Radiation_Batch=NULL


##############################################################
################# Run & set correction (on Irradiated samples)
##############################################################
######## we separate low and high dose to include the dose in Gy as a covariate

################################ Low dose ######################################
Raw_low_dose_irradiated_samples=Raw_pc[,grep("Sample_ID|Run_set|Duplicate|Staining_date|Timepoint|Radiation_type|Radiation_Batch|Age|BMI|Gender|avg_foci_no_outl_low_dose|avg_nfoci_low_dose",colnames(Raw_pc))]

Raw_low_dose_irradiated_samples$Rad_dose_Gy = Raw_low_dose_irradiated_samples$Radiation_type
Raw_low_dose_irradiated_samples$Rad_dose_Gy[Raw_low_dose_irradiated_samples$Rad_dose_Gy == "Fe"] <- low_dose_Fe
Raw_low_dose_irradiated_samples$Rad_dose_Gy[Raw_low_dose_irradiated_samples$Rad_dose_Gy == "Ar"] <- low_dose_Ar
Raw_low_dose_irradiated_samples$Rad_dose_Gy[Raw_low_dose_irradiated_samples$Rad_dose_Gy == "Si"] <- low_dose_Si
Raw_low_dose_irradiated_samples$Rad_dose_Gy[Raw_low_dose_irradiated_samples$Rad_dose_Gy == "Gamma"] <- low_dose_Gamma

Raw_low_dose_irradiated_samples=Raw_low_dose_irradiated_samples[,grep("Sample_ID|Run_set|Duplicate|Staining_date|Timepoint|Radiation_type|Radiation_Batch|Age|BMI|Gender|avg_foci_no_outl_low_dose|avg_nfoci_low_dose|Rad_dose_Gy",colnames(Raw_low_dose_irradiated_samples))]

metadata_save = Raw_low_dose_irradiated_samples[,grep("Sample_ID|Run_set|Duplicate|Staining_date|Timepoint|Radiation_type|Radiation_Batch|Age|BMI|Gender|Rad_dose",colnames(Raw_low_dose_irradiated_samples))]

################### Now, for each run and set value we correct by radiation using coefficient calculated on controls
Irradiated_Responses_Run_set_1 = Raw_low_dose_irradiated_samples %>% filter(Raw_low_dose_irradiated_samples$Run_set_batch == 1)
Irradiated_Responses_Run_set_2 = Raw_low_dose_irradiated_samples %>% filter(Raw_low_dose_irradiated_samples$Run_set_batch == 2)
Irradiated_Responses_Run_set_3 = Raw_low_dose_irradiated_samples %>% filter(Raw_low_dose_irradiated_samples$Run_set_batch == 3)
Irradiated_Responses_Run_set_4 = Raw_low_dose_irradiated_samples %>% filter(Raw_low_dose_irradiated_samples$Run_set_batch == 4)
Irradiated_Responses_Run_set_5 = Raw_low_dose_irradiated_samples %>% filter(Raw_low_dose_irradiated_samples$Run_set_batch == 5)
Irradiated_Responses_Run_set_6 = Raw_low_dose_irradiated_samples %>% filter(Raw_low_dose_irradiated_samples$Run_set_batch == 6)

##### Run_set_1
# create arguments 
metadata_save_1=Irradiated_Responses_Run_set_1[,grep("Sample_ID|Run|Duplicate|Staining|Rad_dose_Gy|Radiation|Timepoint|Age|BMI|Gender",colnames(Irradiated_Responses_Run_set_1))]
metadata=Irradiated_Responses_Run_set_1[,grep("Sample_ID|Rad_dose_Gy|Timepoint|Age|BMI|Gender",colnames(Irradiated_Responses_Run_set_1))]
metadata$BMI_group=NULL
edata_Irradiated=Irradiated_Responses_Run_set_1[,grep("avg_nfoci|avg_foci_no_outl",colnames(Irradiated_Responses_Run_set_1))]
edata_Irradiated=t(edata_Irradiated)
modcombat = model.matrix(~1, data= metadata) 
Batch_C= Irradiated_Responses_Run_set_1$Radiation_Batch
Combat_custom_Rad_correction <- ComBat_custom(dat=edata_Irradiated, batch=Batch_C, custom.gamma=Gamma_factor_Run_set_1, custom.delta=Delta_factor_Run_set_1, mod=modcombat, par.prior=TRUE, prior.plots=FALSE)
#
Rad_Corrected_Irrad_Samples_Run_Set_1 = t(Combat_custom_Rad_correction)
Rad_Corrected_Irrad_Samples_Run_Set_1=cbind(Rad_Corrected_Irrad_Samples_Run_Set_1, metadata_save_1)

##### Run_set_2
# create arguments 
metadata_save_2=Irradiated_Responses_Run_set_2[,grep("Sample_ID|Run|Duplicate|Staining|Rad_dose_Gy|Radiation|Timepoint|Age|BMI|Gender",colnames(Irradiated_Responses_Run_set_2))]
metadata=Irradiated_Responses_Run_set_2[,grep("Sample_ID|Rad_dose_Gy|Timepoint|Age|BMI|Gender",colnames(Irradiated_Responses_Run_set_2))]
metadata$BMI_group=NULL
edata_Irradiated=Irradiated_Responses_Run_set_2[,grep("avg_nfoci|avg_foci_no_outl",colnames(Irradiated_Responses_Run_set_2))]
edata_Irradiated=t(edata_Irradiated)
modcombat = model.matrix(~1, data= metadata) 
Batch_C= Irradiated_Responses_Run_set_2$Radiation_Batch
Combat_custom_Rad_correction <- ComBat_custom(dat=edata_Irradiated, batch=Batch_C, custom.gamma=Gamma_factor_Run_set_2, custom.delta=Delta_factor_Run_set_2, mod=modcombat, par.prior=TRUE, prior.plots=FALSE)
#
Rad_Corrected_Irrad_Samples_Run_Set_2 = t(Combat_custom_Rad_correction)
Rad_Corrected_Irrad_Samples_Run_Set_2=cbind(Rad_Corrected_Irrad_Samples_Run_Set_2, metadata_save_2)


##### Run_set_3
# create arguments 
metadata_save_3=Irradiated_Responses_Run_set_3[,grep("Sample_ID|Run|Duplicate|Staining|Rad_dose_Gy|Radiation|Timepoint|Age|BMI|Gender",colnames(Irradiated_Responses_Run_set_3))]
metadata=Irradiated_Responses_Run_set_3[,grep("Sample_ID|Rad_dose_Gy|Timepoint|Age|BMI|Gender",colnames(Irradiated_Responses_Run_set_3))]
metadata$BMI_group=NULL
edata_Irradiated=Irradiated_Responses_Run_set_3[,grep("avg_nfoci|avg_foci_no_outl",colnames(Irradiated_Responses_Run_set_3))]
edata_Irradiated=t(edata_Irradiated)
modcombat = model.matrix(~1, data= metadata) 
Batch_C= Irradiated_Responses_Run_set_3$Radiation_Batch
Combat_custom_Rad_correction <- ComBat_custom(dat=edata_Irradiated, batch=Batch_C, custom.gamma=Gamma_factor_Run_set_3, custom.delta=Delta_factor_Run_set_3, mod=modcombat, par.prior=TRUE, prior.plots=FALSE)
#
Rad_Corrected_Irrad_Samples_Run_Set_3 = t(Combat_custom_Rad_correction)
Rad_Corrected_Irrad_Samples_Run_Set_3=cbind(Rad_Corrected_Irrad_Samples_Run_Set_3, metadata_save_3)


##### Run_set_4
# create arguments 
metadata_save_4=Irradiated_Responses_Run_set_4[,grep("Sample_ID|Run|Duplicate|Staining|Rad_dose_Gy|Radiation|Timepoint|Age|BMI|Gender",colnames(Irradiated_Responses_Run_set_4))]
metadata=Irradiated_Responses_Run_set_4[,grep("Sample_ID|Rad_dose_Gy|Timepoint|Age|BMI|Gender",colnames(Irradiated_Responses_Run_set_4))]
metadata$BMI_group=NULL
edata_Irradiated=Irradiated_Responses_Run_set_4[,grep("avg_nfoci|avg_foci_no_outl",colnames(Irradiated_Responses_Run_set_4))]
edata_Irradiated=t(edata_Irradiated)
modcombat = model.matrix(~1, data= metadata) 
Batch_C= Irradiated_Responses_Run_set_4$Radiation_Batch
Combat_custom_Rad_correction <- ComBat_custom(dat=edata_Irradiated, batch=Batch_C, custom.gamma=Gamma_factor_Run_set_4, custom.delta=Delta_factor_Run_set_4, mod=modcombat, par.prior=TRUE, prior.plots=FALSE)
#
Rad_Corrected_Irrad_Samples_Run_Set_4 = t(Combat_custom_Rad_correction)
Rad_Corrected_Irrad_Samples_Run_Set_4=cbind(Rad_Corrected_Irrad_Samples_Run_Set_4, metadata_save_4)


##### Run_set_5
# create arguments 
metadata_save_5=Irradiated_Responses_Run_set_5[,grep("Sample_ID|Run|Duplicate|Staining|Rad_dose_Gy|Radiation|Timepoint|Age|BMI|Gender",colnames(Irradiated_Responses_Run_set_5))]
metadata=Irradiated_Responses_Run_set_5[,grep("Sample_ID|Rad_dose_Gy|Timepoint|Age|BMI|Gender",colnames(Irradiated_Responses_Run_set_5))]
metadata$BMI_group=NULL
edata_Irradiated=Irradiated_Responses_Run_set_5[,grep("avg_nfoci|avg_foci_no_outl",colnames(Irradiated_Responses_Run_set_5))]
edata_Irradiated=t(edata_Irradiated)
modcombat = model.matrix(~1, data= metadata) 
Batch_C= Irradiated_Responses_Run_set_5$Radiation_Batch
Combat_custom_Rad_correction <- ComBat_custom(dat=edata_Irradiated, batch=Batch_C, custom.gamma=Gamma_factor_Run_set_5, custom.delta=Delta_factor_Run_set_5, mod=modcombat, par.prior=TRUE, prior.plots=FALSE)
#
Rad_Corrected_Irrad_Samples_Run_Set_5 = t(Combat_custom_Rad_correction)
Rad_Corrected_Irrad_Samples_Run_Set_5=cbind(Rad_Corrected_Irrad_Samples_Run_Set_5, metadata_save_5)

##### Run_set_6
# create arguments 
metadata_save_6=Irradiated_Responses_Run_set_6[,grep("Sample_ID|Run|Duplicate|Staining|Rad_dose_Gy|Radiation|Timepoint|Age|BMI|Gender",colnames(Irradiated_Responses_Run_set_6))]
metadata=Irradiated_Responses_Run_set_6[,grep("Sample_ID|Rad_dose_Gy|Timepoint|Age|BMI|Gender",colnames(Irradiated_Responses_Run_set_6))]
metadata$BMI_group=NULL
edata_Irradiated=Irradiated_Responses_Run_set_6[,grep("avg_nfoci|avg_foci_no_outl",colnames(Irradiated_Responses_Run_set_6))]
edata_Irradiated=t(edata_Irradiated)
modcombat = model.matrix(~1, data= metadata) 
Batch_C= Irradiated_Responses_Run_set_6$Radiation_Batch
Combat_custom_Rad_correction <- ComBat_custom(dat=edata_Irradiated, batch=Batch_C, custom.gamma=Gamma_factor_Run_set_6, custom.delta=Delta_factor_Run_set_6, mod=modcombat, par.prior=TRUE, prior.plots=FALSE)
#
Rad_Corrected_Irrad_Samples_Run_Set_6 = t(Combat_custom_Rad_correction)
Rad_Corrected_Irrad_Samples_Run_Set_6=cbind(Rad_Corrected_Irrad_Samples_Run_Set_6, metadata_save_6)



########## Now we regroup run/set and radiation corrected irradiated samples 
Corrected_low_dose_irradiated_samples=bind_rows(Rad_Corrected_Irrad_Samples_Run_Set_1, Rad_Corrected_Irrad_Samples_Run_Set_2, 
                                       Rad_Corrected_Irrad_Samples_Run_Set_3, Rad_Corrected_Irrad_Samples_Run_Set_4,
                                       Rad_Corrected_Irrad_Samples_Run_Set_5, Rad_Corrected_Irrad_Samples_Run_Set_6)

Corrected_low_dose_irradiated_samples$Run_set_batch=NULL
Corrected_low_dose_irradiated_samples$Radiation_Batch=NULL
Corrected_low_dose_irradiated_samples$Rad_dose_Gy=NULL


################################ high dose ######################################
Raw_high_dose_irradiated_samples=Raw_pc[,grep("Sample_ID|Run_set|Duplicate|Staining_date|Timepoint|Radiation_type|Radiation_Batch|Age|BMI|Gender|avg_foci_no_outl_high_dose|avg_nfoci_high_dose",colnames(Raw_pc))]

Raw_high_dose_irradiated_samples$Rad_dose_Gy = Raw_high_dose_irradiated_samples$Radiation_type
Raw_high_dose_irradiated_samples$Rad_dose_Gy[Raw_high_dose_irradiated_samples$Rad_dose_Gy == "Fe"] <- high_dose_Fe
Raw_high_dose_irradiated_samples$Rad_dose_Gy[Raw_high_dose_irradiated_samples$Rad_dose_Gy == "Ar"] <- high_dose_Ar
Raw_high_dose_irradiated_samples$Rad_dose_Gy[Raw_high_dose_irradiated_samples$Rad_dose_Gy == "Si"] <- high_dose_Si
Raw_high_dose_irradiated_samples$Rad_dose_Gy[Raw_high_dose_irradiated_samples$Rad_dose_Gy == "Gamma"] <- high_dose_Gamma

Raw_high_dose_irradiated_samples=Raw_high_dose_irradiated_samples[,grep("Sample_ID|Run_set|Duplicate|Staining_date|Timepoint|Radiation_type|Radiation_Batch|Age|BMI|Gender|avg_foci_no_outl_high_dose|avg_nfoci_high_dose|Rad_dose_Gy",colnames(Raw_high_dose_irradiated_samples))]

metadata_save = Raw_high_dose_irradiated_samples[,grep("Sample_ID|Run_set|Duplicate|Staining_date|Timepoint|Radiation_type|Radiation_Batch|Age|BMI|Gender|Rad_dose",colnames(Raw_high_dose_irradiated_samples))]

################### Now, for each run and set value we correct by radiation
# Mentioned before, but here too lines must be added for each new Run_set irradiated/imaged samples considered in future analysis
Irradiated_Responses_Run_set_1 = Raw_high_dose_irradiated_samples %>% filter(Raw_high_dose_irradiated_samples$Run_set_batch == 1)
Irradiated_Responses_Run_set_2 = Raw_high_dose_irradiated_samples %>% filter(Raw_high_dose_irradiated_samples$Run_set_batch == 2)
Irradiated_Responses_Run_set_3 = Raw_high_dose_irradiated_samples %>% filter(Raw_high_dose_irradiated_samples$Run_set_batch == 3)
Irradiated_Responses_Run_set_4 = Raw_high_dose_irradiated_samples %>% filter(Raw_high_dose_irradiated_samples$Run_set_batch == 4)
Irradiated_Responses_Run_set_5 = Raw_high_dose_irradiated_samples %>% filter(Raw_high_dose_irradiated_samples$Run_set_batch == 5)
Irradiated_Responses_Run_set_6 = Raw_high_dose_irradiated_samples %>% filter(Raw_high_dose_irradiated_samples$Run_set_batch == 6)


##### Run_set_1
# create arguments 
metadata_save_1=Irradiated_Responses_Run_set_1[,grep("Sample_ID|Run|Duplicate|Staining|Rad_dose_Gy|Radiation|Timepoint|Age|BMI|Gender",colnames(Irradiated_Responses_Run_set_1))]
metadata=Irradiated_Responses_Run_set_1[,grep("Sample_ID|Rad_dose_Gy|Timepoint|Age|BMI|Gender",colnames(Irradiated_Responses_Run_set_1))]
metadata$BMI_group=NULL
edata_Irradiated=Irradiated_Responses_Run_set_1[,grep("avg_nfoci|avg_foci_no_outl",colnames(Irradiated_Responses_Run_set_1))]
edata_Irradiated=t(edata_Irradiated)
modcombat = model.matrix(~1, data= metadata) 
Batch_C= Irradiated_Responses_Run_set_1$Radiation_Batch
Combat_custom_Rad_correction <- ComBat_custom(dat=edata_Irradiated, batch=Batch_C, custom.gamma=Gamma_factor_Run_set_1, custom.delta=Delta_factor_Run_set_1, mod=modcombat, par.prior=TRUE, prior.plots=FALSE)
#
Rad_Corrected_Irrad_Samples_Run_Set_1 = t(Combat_custom_Rad_correction)
Rad_Corrected_Irrad_Samples_Run_Set_1=cbind(Rad_Corrected_Irrad_Samples_Run_Set_1, metadata_save_1)

##### Run_set_2
# create arguments 
metadata_save_2=Irradiated_Responses_Run_set_2[,grep("Sample_ID|Run|Duplicate|Staining|Rad_dose_Gy|Radiation|Timepoint|Age|BMI|Gender",colnames(Irradiated_Responses_Run_set_2))]
metadata=Irradiated_Responses_Run_set_2[,grep("Sample_ID|Rad_dose_Gy|Timepoint|Age|BMI|Gender",colnames(Irradiated_Responses_Run_set_2))]
metadata$BMI_group=NULL
edata_Irradiated=Irradiated_Responses_Run_set_2[,grep("avg_nfoci|avg_foci_no_outl",colnames(Irradiated_Responses_Run_set_2))]
edata_Irradiated=t(edata_Irradiated)
modcombat = model.matrix(~1, data= metadata) 
Batch_C= Irradiated_Responses_Run_set_2$Radiation_Batch
Combat_custom_Rad_correction <- ComBat_custom(dat=edata_Irradiated, batch=Batch_C, custom.gamma=Gamma_factor_Run_set_2, custom.delta=Delta_factor_Run_set_2, mod=modcombat, par.prior=TRUE, prior.plots=FALSE)
#
Rad_Corrected_Irrad_Samples_Run_Set_2 = t(Combat_custom_Rad_correction)
Rad_Corrected_Irrad_Samples_Run_Set_2=cbind(Rad_Corrected_Irrad_Samples_Run_Set_2, metadata_save_2)


##### Run_set_3
# create arguments 
metadata_save_3=Irradiated_Responses_Run_set_3[,grep("Sample_ID|Run|Duplicate|Staining|Rad_dose_Gy|Radiation|Timepoint|Age|BMI|Gender",colnames(Irradiated_Responses_Run_set_3))]
metadata=Irradiated_Responses_Run_set_3[,grep("Sample_ID|Rad_dose_Gy|Timepoint|Age|BMI|Gender",colnames(Irradiated_Responses_Run_set_3))]
metadata$BMI_group=NULL
edata_Irradiated=Irradiated_Responses_Run_set_3[,grep("avg_nfoci|avg_foci_no_outl",colnames(Irradiated_Responses_Run_set_3))]
edata_Irradiated=t(edata_Irradiated)
modcombat = model.matrix(~1, data= metadata) 
Batch_C= Irradiated_Responses_Run_set_3$Radiation_Batch
Combat_custom_Rad_correction <- ComBat_custom(dat=edata_Irradiated, batch=Batch_C, custom.gamma=Gamma_factor_Run_set_3, custom.delta=Delta_factor_Run_set_3, mod=modcombat, par.prior=TRUE, prior.plots=FALSE)
#
Rad_Corrected_Irrad_Samples_Run_Set_3 = t(Combat_custom_Rad_correction)
Rad_Corrected_Irrad_Samples_Run_Set_3=cbind(Rad_Corrected_Irrad_Samples_Run_Set_3, metadata_save_3)

##### Run_set_4
# create arguments 
metadata_save_4=Irradiated_Responses_Run_set_4[,grep("Sample_ID|Run|Duplicate|Staining|Rad_dose_Gy|Radiation|Timepoint|Age|BMI|Gender",colnames(Irradiated_Responses_Run_set_4))]
metadata=Irradiated_Responses_Run_set_4[,grep("Sample_ID|Rad_dose_Gy|Timepoint|Age|BMI|Gender",colnames(Irradiated_Responses_Run_set_4))]
metadata$BMI_group=NULL
edata_Irradiated=Irradiated_Responses_Run_set_4[,grep("avg_nfoci|avg_foci_no_outl",colnames(Irradiated_Responses_Run_set_4))]
edata_Irradiated=t(edata_Irradiated)
modcombat = model.matrix(~1, data= metadata) 
Batch_C= Irradiated_Responses_Run_set_4$Radiation_Batch
Combat_custom_Rad_correction <- ComBat_custom(dat=edata_Irradiated, batch=Batch_C, custom.gamma=Gamma_factor_Run_set_4, custom.delta=Delta_factor_Run_set_4, mod=modcombat, par.prior=TRUE, prior.plots=FALSE)
#
Rad_Corrected_Irrad_Samples_Run_Set_4 = t(Combat_custom_Rad_correction)
Rad_Corrected_Irrad_Samples_Run_Set_4=cbind(Rad_Corrected_Irrad_Samples_Run_Set_4, metadata_save_4)


##### Run_set_5
# create arguments 
metadata_save_5=Irradiated_Responses_Run_set_5[,grep("Sample_ID|Run|Duplicate|Staining|Rad_dose_Gy|Radiation|Timepoint|Age|BMI|Gender",colnames(Irradiated_Responses_Run_set_5))]
metadata=Irradiated_Responses_Run_set_5[,grep("Sample_ID|Rad_dose_Gy|Timepoint|Age|BMI|Gender",colnames(Irradiated_Responses_Run_set_5))]
metadata$BMI_group=NULL
edata_Irradiated=Irradiated_Responses_Run_set_5[,grep("avg_nfoci|avg_foci_no_outl",colnames(Irradiated_Responses_Run_set_5))]
edata_Irradiated=t(edata_Irradiated)
modcombat = model.matrix(~1, data= metadata) 
Batch_C= Irradiated_Responses_Run_set_5$Radiation_Batch
Combat_custom_Rad_correction <- ComBat_custom(dat=edata_Irradiated, batch=Batch_C, custom.gamma=Gamma_factor_Run_set_5, custom.delta=Delta_factor_Run_set_5, mod=modcombat, par.prior=TRUE, prior.plots=FALSE)
#
Rad_Corrected_Irrad_Samples_Run_Set_5 = t(Combat_custom_Rad_correction)
Rad_Corrected_Irrad_Samples_Run_Set_5=cbind(Rad_Corrected_Irrad_Samples_Run_Set_5, metadata_save_5)


##### Run_set_6
# create arguments 
metadata_save_6=Irradiated_Responses_Run_set_6[,grep("Sample_ID|Run|Duplicate|Staining|Rad_dose_Gy|Radiation|Timepoint|Age|BMI|Gender",colnames(Irradiated_Responses_Run_set_6))]
metadata=Irradiated_Responses_Run_set_6[,grep("Sample_ID|Rad_dose_Gy|Timepoint|Age|BMI|Gender",colnames(Irradiated_Responses_Run_set_6))]
metadata$BMI_group=NULL
edata_Irradiated=Irradiated_Responses_Run_set_6[,grep("avg_nfoci|avg_foci_no_outl",colnames(Irradiated_Responses_Run_set_6))]
edata_Irradiated=t(edata_Irradiated)
modcombat = model.matrix(~1, data= metadata) 
Batch_C= Irradiated_Responses_Run_set_6$Radiation_Batch
Combat_custom_Rad_correction <- ComBat_custom(dat=edata_Irradiated, batch=Batch_C, custom.gamma=Gamma_factor_Run_set_6, custom.delta=Delta_factor_Run_set_6, mod=modcombat, par.prior=TRUE, prior.plots=FALSE)
#
Rad_Corrected_Irrad_Samples_Run_Set_6 = t(Combat_custom_Rad_correction)
Rad_Corrected_Irrad_Samples_Run_Set_6=cbind(Rad_Corrected_Irrad_Samples_Run_Set_6, metadata_save_6)


########## Now we regroup run/set and radiation corrected irradiated samples 
Corrected_high_dose_irradiated_samples=bind_rows(Rad_Corrected_Irrad_Samples_Run_Set_1, Rad_Corrected_Irrad_Samples_Run_Set_2, 
                                       Rad_Corrected_Irrad_Samples_Run_Set_3, Rad_Corrected_Irrad_Samples_Run_Set_4,
                                       Rad_Corrected_Irrad_Samples_Run_Set_5, Rad_Corrected_Irrad_Samples_Run_Set_6)

Corrected_high_dose_irradiated_samples$Run_set_batch=NULL
Corrected_high_dose_irradiated_samples$Radiation_Batch=NULL
Corrected_high_dose_irradiated_samples$Rad_dose_Gy=NULL


#### Data formating in order to do the correction using the right control for all experimental conditions
## controls
Controls_4h = Corrected_controls %>% filter(Corrected_controls$Timepoint =="4h")
Controls_4h_Fe =Controls_4h %>% filter(Controls_4h$Radiation_type =="Fe")
Controls_4h_Ar = Controls_4h %>% filter(Controls_4h$Radiation_type =="Ar")
Controls_4h_Si = Controls_4h %>% filter(Controls_4h$Radiation_type =="Si")
Controls_4h_Gamma = Controls_4h %>% filter(Controls_4h$Radiation_type =="Gamma")
#
Controls_24h = Corrected_controls %>% filter(Corrected_controls$Timepoint=="24h")
Controls_24h_Fe = Controls_24h %>% filter(Controls_24h$Radiation_type=="Fe")
Controls_24h_Ar = Controls_24h%>% filter(Controls_24h$Radiation_type=="Ar")
Controls_24h_Si =Controls_24h %>% filter(Controls_24h$Radiation_type=="Si")
Controls_24h_Gamma = Controls_24h %>% filter(Controls_24h$Radiation_type=="Gamma")
## Low dose
LD_4h = Corrected_low_dose_irradiated_samples %>% filter(Corrected_low_dose_irradiated_samples$Timepoint=="4h")
LD_4h_Fe = LD_4h %>% filter(LD_4h$Radiation_type=="Fe")
LD_4h_Fe=LD_4h_Fe[,grepl("Sample_ID|avg_nfoci_low|Run_set|Duplicate",colnames(LD_4h_Fe))]
LD_4h_Ar = LD_4h %>% filter(LD_4h$Radiation_type=="Ar")
LD_4h_Ar=LD_4h_Ar[,grepl("Sample_ID|avg_nfoci_low|Run_set|Duplicate",colnames(LD_4h_Ar))]
LD_4h_Si = LD_4h %>% filter(LD_4h$Radiation_type=="Si")
LD_4h_Si=LD_4h_Si[,grepl("Sample_ID|avg_nfoci_low|Run_set|Duplicate",colnames(LD_4h_Si))]
LD_4h_Gamma = LD_4h %>% filter(LD_4h$Radiation_type=="Gamma")
LD_4h_Gamma=LD_4h_Gamma[,grepl("Sample_ID|avg_nfoci_low|Run_set|Duplicate",colnames(LD_4h_Gamma))]
#
LD_24h = Corrected_low_dose_irradiated_samples %>% filter(Corrected_low_dose_irradiated_samples$Timepoint=="24h")
LD_24h_Fe = LD_24h %>% filter(LD_24h$Radiation_type=="Fe")
LD_24h_Fe=LD_24h_Fe[,grepl("Sample_ID|avg_nfoci_low|Run_set|Duplicate",colnames(LD_24h_Fe))]
LD_24h_Ar = LD_24h %>% filter(LD_24h$Radiation_type=="Ar")
LD_24h_Ar=LD_24h_Ar[,grepl("Sample_ID|avg_nfoci_low|Run_set|Duplicate",colnames(LD_24h_Ar))]
LD_24h_Si = LD_24h %>% filter(LD_24h$Radiation_type=="Si")
LD_24h_Si=LD_24h_Si[,grepl("Sample_ID|avg_nfoci_low|Run_set|Duplicate",colnames(LD_24h_Si))]
LD_24h_Gamma = LD_24h %>% filter(LD_24h$Radiation_type=="Gamma")
LD_24h_Gamma=LD_24h_Gamma[,grepl("Sample_ID|avg_nfoci_low|Run_set|Duplicate",colnames(LD_24h_Gamma))]
## High dose
HD_4h = Corrected_high_dose_irradiated_samples %>% filter(Corrected_high_dose_irradiated_samples$Timepoint=="4h")
HD_4h_Fe = HD_4h %>% filter(HD_4h$Radiation_type=="Fe")
HD_4h_Fe=HD_4h_Fe[,grepl("Sample_ID|avg_nfoci_high|Run_set|Duplicate",colnames(HD_4h_Fe))]
HD_4h_Ar = HD_4h %>% filter(HD_4h$Radiation_type=="Ar")
HD_4h_Ar=HD_4h_Ar[,grepl("Sample_ID|avg_nfoci_high|Run_set|Duplicate",colnames(HD_4h_Ar))]
HD_4h_Si = HD_4h %>% filter(HD_4h$Radiation_type=="Si")
HD_4h_Si=HD_4h_Si[,grepl("Sample_ID|avg_nfoci_high|Run_set|Duplicate",colnames(HD_4h_Si))]
HD_4h_Gamma = HD_4h %>% filter(HD_4h$Radiation_type=="Gamma")
HD_4h_Gamma=HD_4h_Gamma[,grepl("Sample_ID|avg_nfoci_high|Run_set|Duplicate",colnames(HD_4h_Gamma))]
#
HD_24h = Corrected_high_dose_irradiated_samples %>% filter(Corrected_high_dose_irradiated_samples$Timepoint=="24h")
HD_24h_Fe = HD_24h %>% filter(HD_24h$Radiation_type=="Fe")
HD_24h_Fe=HD_24h_Fe[,grepl("Sample_ID|avg_nfoci_high|Run_set|Duplicate",colnames(HD_24h_Fe))]
HD_24h_Ar = HD_24h %>% filter(HD_24h$Radiation_type=="Ar")
HD_24h_Ar=HD_24h_Ar[,grepl("Sample_ID|avg_nfoci_high|Run_set|Duplicate",colnames(HD_24h_Ar))]
HD_24h_Si = HD_24h %>% filter(HD_24h$Radiation_type=="Si")
HD_24h_Si=HD_24h_Si[,grepl("Sample_ID|avg_nfoci_high|Run_set|Duplicate",colnames(HD_24h_Si))]
HD_24h_Gamma = HD_24h %>% filter(HD_24h$Radiation_type=="Gamma")
HD_24h_Gamma=HD_24h_Gamma[,grepl("Sample_ID|avg_nfoci_high|Run_set|Duplicate",colnames(HD_24h_Gamma))]

## Regroup 
Correct_Fe_4h=merge(Controls_4h_Fe, LD_4h_Fe, by=c("Sample_ID", "Duplicate", "Run_set"))
Correct_Fe_4h=merge(Correct_Fe_4h, HD_4h_Fe, by=c("Sample_ID", "Duplicate", "Run_set"))
#
Correct_Ar_4h=merge(Controls_4h_Ar, LD_4h_Ar, by=c("Sample_ID", "Duplicate", "Run_set"))
Correct_Ar_4h=merge(Correct_Ar_4h, HD_4h_Ar, by=c("Sample_ID", "Duplicate", "Run_set"))
#
Correct_Si_4h=merge(Controls_4h_Si, LD_4h_Si, by=c("Sample_ID", "Duplicate", "Run_set"))
Correct_Si_4h=merge(Correct_Si_4h, HD_4h_Si, by=c("Sample_ID", "Duplicate", "Run_set"))
#
Correct_Gamma_4h=merge(Controls_4h_Gamma, LD_4h_Gamma, by=c("Sample_ID", "Duplicate", "Run_set"))
Correct_Gamma_4h=merge(Correct_Gamma_4h, HD_4h_Gamma, by=c("Sample_ID", "Duplicate", "Run_set"))
#
Correct_Fe_24h=merge(Controls_24h_Fe, LD_24h_Fe, by=c("Sample_ID", "Duplicate", "Run_set"))
Correct_Fe_24h=merge(Correct_Fe_24h, HD_24h_Fe, by=c("Sample_ID", "Duplicate", "Run_set"))
#
Correct_Ar_24h=merge(Controls_24h_Ar, LD_24h_Ar, by=c("Sample_ID", "Duplicate", "Run_set"))
Correct_Ar_24h=merge(Correct_Ar_24h, HD_24h_Ar, by=c("Sample_ID", "Duplicate", "Run_set"))
#
Correct_Si_24h=merge(Controls_24h_Si, LD_24h_Si, by=c("Sample_ID", "Duplicate", "Run_set"))
Correct_Si_24h=merge(Correct_Si_24h, HD_24h_Si, by=c("Sample_ID", "Duplicate", "Run_set"))
#
Correct_Gamma_24h=merge(Controls_24h_Gamma, LD_24h_Gamma, by=c("Sample_ID", "Duplicate", "Run_set"))
Correct_Gamma_24h=merge(Correct_Gamma_24h, HD_24h_Gamma, by=c("Sample_ID", "Duplicate", "Run_set"))


#### Regroup everything into 1 table
Corrected_DNA_Damage= bind_rows(Correct_Fe_4h, Correct_Fe_24h,
                                Correct_Ar_4h, Correct_Ar_24h,
                                Correct_Si_4h, Correct_Si_24h,
                                Correct_Gamma_4h, Correct_Gamma_24h)

Corrected_DNA_Damage$avg_foci_no_outl_0=NULL

#### The correction may generate negative value => we fix those negative value to 0 
Corrected_DNA_Damage$avg_nfoci_0[Corrected_DNA_Damage$avg_nfoci_0 < 0] <- 0 
Corrected_DNA_Damage$avg_nfoci_low_dose[Corrected_DNA_Damage$avg_nfoci_low_dose < 0] <-  0 
Corrected_DNA_Damage$avg_nfoci_high_dose[Corrected_DNA_Damage$avg_nfoci_high_dose < 0] <-  0 

Corrected_DNA_Damage_HT= Corrected_DNA_Damage
#Corrected_DNA_Damage_CD7= Corrected_DNA_Damage


### Correction Step 2 
### Now we calculate the Z-score only on the 10p that overlapp in 18B and 19A
# Select the 10 people that overlap in these two run
Subject_18BS2_19AS1 = c(1214, 1215,1216,1217,1218,1219,1220,1221,1222,1223)
RIF_correct_19A_18B_10p = Corrected_DNA_Damage %>% filter(Corrected_DNA_Damage$Sample_ID %in% Subject_18BS2_19AS1 )

#### Z-score for 19A
Samp_19A_10p = RIF_correct_19A_18B_10p %>% filter(RIF_correct_19A_18B_10p$Run_set =="Run_19A_Set_1")

## For Controls 
Controls_19A= Samp_19A_10p
Controls_19A$avg_nfoci_low_dose=NULL
Controls_19A$avg_nfoci_high_dose=NULL
Controls_19A$nfoci_high_dose_norm=NULL 
Controls_19A$nfoci_low_dose_norm=NULL 
#
### 4h 
control_19A_4h = Controls_19A %>% filter(Controls_19A$Timepoint=="4h")
#
control_19A_4h_Fe = control_19A_4h %>% filter(control_19A_4h$Radiation_type=="Fe")
control_19A_4h_Ar = control_19A_4h %>% filter(control_19A_4h$Radiation_type=="Ar")
control_19A_4h_Si = control_19A_4h %>% filter(control_19A_4h$Radiation_type=="Si")
control_19A_4h_Gamma = control_19A_4h %>% filter(control_19A_4h$Radiation_type=="Gamma")
### 24h 
control_19A_24h = Controls_19A %>% filter(Controls_19A$Timepoint=="24h")
#
control_19A_24h_Fe = control_19A_24h %>% filter(control_19A_24h$Radiation_type=="Fe")
control_19A_24h_Ar = control_19A_24h %>% filter(control_19A_24h$Radiation_type=="Ar")
control_19A_24h_Si = control_19A_24h %>% filter(control_19A_24h$Radiation_type=="Si")
control_19A_24h_Gamma = control_19A_24h %>% filter(control_19A_24h$Radiation_type=="Gamma")
### For each conditions (radiation type/time point) calculate mean and std
####### Mean
# 4h
Mean_ref_19A_Cont_Fe_4h = mean(NaRV.omit(control_19A_4h_Fe$avg_nfoci_0))
Mean_ref_19A_Cont_Ar_4h = mean(NaRV.omit(control_19A_4h_Ar$avg_nfoci_0))
Mean_ref_19A_Cont_Si_4h = mean(NaRV.omit(control_19A_4h_Si$avg_nfoci_0))
Mean_ref_19A_Cont_Gamma_4h = mean(NaRV.omit(control_19A_4h_Gamma$avg_nfoci_0))
# 24h
Mean_ref_19A_Cont_Fe_24h = mean(NaRV.omit(control_19A_24h_Fe$avg_nfoci_0))
Mean_ref_19A_Cont_Ar_24h = mean(NaRV.omit(control_19A_24h_Ar$avg_nfoci_0))
Mean_ref_19A_Cont_Si_24h = mean(NaRV.omit(control_19A_24h_Si$avg_nfoci_0))
Mean_ref_19A_Cont_Gamma_24h = mean(NaRV.omit(control_19A_24h_Gamma$avg_nfoci_0))
####### sd
# 4h
Std_ref_19A_Cont_Fe_4h = sd(NaRV.omit(control_19A_4h_Fe$avg_nfoci_0))
Std_ref_19A_Cont_Ar_4h = sd(NaRV.omit(control_19A_4h_Ar$avg_nfoci_0))
Std_ref_19A_Cont_Si_4h = sd(NaRV.omit(control_19A_4h_Si$avg_nfoci_0))
Std_ref_19A_Cont_Gamma_4h = sd(NaRV.omit(control_19A_4h_Gamma$avg_nfoci_0))
# 24h
Std_ref_19A_Cont_Fe_24h = sd(NaRV.omit(control_19A_24h_Fe$avg_nfoci_0))
Std_ref_19A_Cont_Ar_24h = sd(NaRV.omit(control_19A_24h_Ar$avg_nfoci_0))
Std_ref_19A_Cont_Si_24h = sd(NaRV.omit(control_19A_24h_Si$avg_nfoci_0))
Std_ref_19A_Cont_Gamma_24h = sd(NaRV.omit(control_19A_24h_Gamma$avg_nfoci_0))
#
#
## For Low dose irradiated samples
LD_19A= Samp_19A_10p
LD_19A$avg_nfoci_0=NULL
LD_19A$avg_nfoci_high_dose=NULL
LD_19A$nfoci_high_dose_norm=NULL 
LD_19A$nfoci_low_dose_norm=NULL 
LD_19A$nfoci_0=NULL 
#
### 4h 
LD_19A_4h = LD_19A %>% filter(LD_19A$Timepoint=="4h")
#
LD_19A_4h_Fe = LD_19A_4h %>% filter(LD_19A_4h$Radiation_type=="Fe")
LD_19A_4h_Ar = LD_19A_4h %>% filter(LD_19A_4h$Radiation_type=="Ar")
LD_19A_4h_Si = LD_19A_4h %>% filter(LD_19A_4h$Radiation_type=="Si")
LD_19A_4h_Gamma = LD_19A_4h %>% filter(LD_19A_4h$Radiation_type=="Gamma")
### 24h 
LD_19A_24h = LD_19A %>% filter(LD_19A$Timepoint=="24h")
#
LD_19A_24h_Fe = LD_19A_24h %>% filter(LD_19A_24h$Radiation_type=="Fe")
LD_19A_24h_Ar = LD_19A_24h %>% filter(LD_19A_24h$Radiation_type=="Ar")
LD_19A_24h_Si = LD_19A_24h %>% filter(LD_19A_24h$Radiation_type=="Si")
LD_19A_24h_Gamma = LD_19A_24h %>% filter(LD_19A_24h$Radiation_type=="Gamma")
### For each conditions (radiation type/time point) calculate mean and std
####### Mean
# 4h
Mean_ref_19A_LD_Fe_4h = mean(NaRV.omit(LD_19A_4h_Fe$avg_nfoci_low_dose))
Mean_ref_19A_LD_Ar_4h = mean(NaRV.omit(LD_19A_4h_Ar$avg_nfoci_low_dose))
Mean_ref_19A_LD_Si_4h = mean(NaRV.omit(LD_19A_4h_Si$avg_nfoci_low_dose))
Mean_ref_19A_LD_Gamma_4h = mean(NaRV.omit(LD_19A_4h_Gamma$avg_nfoci_low_dose))
# 24h
Mean_ref_19A_LD_Fe_24h = mean(NaRV.omit(LD_19A_24h_Fe$avg_nfoci_low_dose))
Mean_ref_19A_LD_Ar_24h = mean(NaRV.omit(LD_19A_24h_Ar$avg_nfoci_low_dose))
Mean_ref_19A_LD_Si_24h = mean(NaRV.omit(LD_19A_24h_Si$avg_nfoci_low_dose))
Mean_ref_19A_LD_Gamma_24h = mean(NaRV.omit(LD_19A_24h_Gamma$avg_nfoci_low_dose))
####### sd
# 4h
Std_ref_19A_LD_Fe_4h = sd(NaRV.omit(LD_19A_4h_Fe$avg_nfoci_low_dose))
Std_ref_19A_LD_Ar_4h = sd(NaRV.omit(LD_19A_4h_Ar$avg_nfoci_low_dose))
Std_ref_19A_LD_Si_4h = sd(NaRV.omit(LD_19A_4h_Si$avg_nfoci_low_dose))
Std_ref_19A_LD_Gamma_4h = sd(NaRV.omit(LD_19A_4h_Gamma$avg_nfoci_low_dose))
# 24h
Std_ref_19A_LD_Fe_24h = sd(NaRV.omit(LD_19A_24h_Fe$avg_nfoci_low_dose))
Std_ref_19A_LD_Ar_24h = sd(NaRV.omit(LD_19A_24h_Ar$avg_nfoci_low_dose))
Std_ref_19A_LD_Si_24h = sd(NaRV.omit(LD_19A_24h_Si$avg_nfoci_low_dose))
Std_ref_19A_LD_Gamma_24h = sd(NaRV.omit(LD_19A_24h_Gamma$avg_nfoci_low_dose))
#
#
## For high dose irradiated samples
HD_19A= Samp_19A_10p
HD_19A$avg_nfoci_0=NULL
HD_19A$avg_nfoci_low_dose=NULL
HD_19A$nfoci_low_dose_norm=NULL 
HD_19A$nfoci_high_dose_norm=NULL 
HD_19A$nfoci_0=NULL 
#
### 4h 
HD_19A_4h = HD_19A %>% filter(HD_19A$Timepoint=="4h")
#
HD_19A_4h_Fe = HD_19A_4h %>% filter(HD_19A_4h$Radiation_type=="Fe")
HD_19A_4h_Ar = HD_19A_4h %>% filter(HD_19A_4h$Radiation_type=="Ar")
HD_19A_4h_Si = HD_19A_4h %>% filter(HD_19A_4h$Radiation_type=="Si")
HD_19A_4h_Gamma = HD_19A_4h %>% filter(HD_19A_4h$Radiation_type=="Gamma")
### 24h 
HD_19A_24h = HD_19A %>% filter(HD_19A$Timepoint=="24h")
#
HD_19A_24h_Fe = HD_19A_24h %>% filter(HD_19A_24h$Radiation_type=="Fe")
HD_19A_24h_Ar = HD_19A_24h %>% filter(HD_19A_24h$Radiation_type=="Ar")
HD_19A_24h_Si = HD_19A_24h %>% filter(HD_19A_24h$Radiation_type=="Si")
HD_19A_24h_Gamma = HD_19A_24h %>% filter(HD_19A_24h$Radiation_type=="Gamma")
### For each conditions (radiation type/time point) calculate mean and std
####### Mean
# 4h
Mean_ref_19A_HD_Fe_4h = mean(NaRV.omit(HD_19A_4h_Fe$avg_nfoci_high_dose))
Mean_ref_19A_HD_Ar_4h = mean(NaRV.omit(HD_19A_4h_Ar$avg_nfoci_high_dose))
Mean_ref_19A_HD_Si_4h = mean(NaRV.omit(HD_19A_4h_Si$avg_nfoci_high_dose))
Mean_ref_19A_HD_Gamma_4h = mean(NaRV.omit(HD_19A_4h_Gamma$avg_nfoci_high_dose))
# 24h
Mean_ref_19A_HD_Fe_24h = mean(NaRV.omit(HD_19A_24h_Fe$avg_nfoci_high_dose))
Mean_ref_19A_HD_Ar_24h = mean(NaRV.omit(HD_19A_24h_Ar$avg_nfoci_high_dose))
Mean_ref_19A_HD_Si_24h = mean(NaRV.omit(HD_19A_24h_Si$avg_nfoci_high_dose))
Mean_ref_19A_HD_Gamma_24h = mean(NaRV.omit(HD_19A_24h_Gamma$avg_nfoci_high_dose))
####### sd
# 4h
Std_ref_19A_HD_Fe_4h = sd(NaRV.omit(HD_19A_4h_Fe$avg_nfoci_high_dose))
Std_ref_19A_HD_Ar_4h = sd(NaRV.omit(HD_19A_4h_Ar$avg_nfoci_high_dose))
Std_ref_19A_HD_Si_4h = sd(NaRV.omit(HD_19A_4h_Si$avg_nfoci_high_dose))
Std_ref_19A_HD_Gamma_4h = sd(NaRV.omit(HD_19A_4h_Gamma$avg_nfoci_high_dose))
# 24h
Std_ref_19A_HD_Fe_24h = sd(NaRV.omit(HD_19A_24h_Fe$avg_nfoci_high_dose))
Std_ref_19A_HD_Ar_24h = sd(NaRV.omit(HD_19A_24h_Ar$avg_nfoci_high_dose))
Std_ref_19A_HD_Si_24h = sd(NaRV.omit(HD_19A_24h_Si$avg_nfoci_high_dose))
Std_ref_19A_HD_Gamma_24h = sd(NaRV.omit(HD_19A_24h_Gamma$avg_nfoci_high_dose))
#
#### Z-score for 18B
Samp_18B_10p = RIF_correct_19A_18B_10p %>% filter(RIF_correct_19A_18B_10p$Run_set =="Run_18B_Set_2")
#
## For Controls 
Controls_18B= Samp_18B_10p
Controls_18B$avg_nfoci_low_dose=NULL
Controls_18B$avg_nfoci_high_dose=NULL
Controls_18B$nfoci_high_dose_norm=NULL 
Controls_18B$nfoci_low_dose_norm=NULL 
#
### 4h 
control_18B_4h = Controls_18B %>% filter(Controls_18B$Timepoint=="4h")
#
control_18B_4h_Fe = control_18B_4h %>% filter(control_18B_4h$Radiation_type=="Fe")
control_18B_4h_Ar = control_18B_4h %>% filter(control_18B_4h$Radiation_type=="Ar")
control_18B_4h_Si = control_18B_4h %>% filter(control_18B_4h$Radiation_type=="Si")
control_18B_4h_Gamma = control_18B_4h %>% filter(control_18B_4h$Radiation_type=="Gamma")
### 24h 
control_18B_24h = Controls_18B %>% filter(Controls_18B$Timepoint=="24h")
#
control_18B_24h_Fe = control_18B_24h %>% filter(control_18B_24h$Radiation_type=="Fe")
control_18B_24h_Ar = control_18B_24h %>% filter(control_18B_24h$Radiation_type=="Ar")
control_18B_24h_Si = control_18B_24h %>% filter(control_18B_24h$Radiation_type=="Si")
control_18B_24h_Gamma = control_18B_24h %>% filter(control_18B_24h$Radiation_type=="Gamma")
### For each conditions (radiation type/time point) calculate mean and std
####### Mean
# 4h
Mean_ref_18B_Cont_Fe_4h = mean(NaRV.omit(control_18B_4h_Fe$avg_nfoci_0))
Mean_ref_18B_Cont_Ar_4h = mean(NaRV.omit(control_18B_4h_Ar$avg_nfoci_0))
Mean_ref_18B_Cont_Si_4h = mean(NaRV.omit(control_18B_4h_Si$avg_nfoci_0))
Mean_ref_18B_Cont_Gamma_4h = mean(NaRV.omit(control_18B_4h_Gamma$avg_nfoci_0))
# 24h
Mean_ref_18B_Cont_Fe_24h = mean(NaRV.omit(control_18B_24h_Fe$avg_nfoci_0))
Mean_ref_18B_Cont_Ar_24h = mean(NaRV.omit(control_18B_24h_Ar$avg_nfoci_0))
Mean_ref_18B_Cont_Si_24h = mean(NaRV.omit(control_18B_24h_Si$avg_nfoci_0))
Mean_ref_18B_Cont_Gamma_24h = mean(NaRV.omit(control_18B_24h_Gamma$avg_nfoci_0))
####### sd
# 4h
Std_ref_18B_Cont_Fe_4h = sd(NaRV.omit(control_18B_4h_Fe$avg_nfoci_0))
Std_ref_18B_Cont_Ar_4h = sd(NaRV.omit(control_18B_4h_Ar$avg_nfoci_0))
Std_ref_18B_Cont_Si_4h = sd(NaRV.omit(control_18B_4h_Si$avg_nfoci_0))
Std_ref_18B_Cont_Gamma_4h = sd(NaRV.omit(control_18B_4h_Gamma$avg_nfoci_0))
# 24h
Std_ref_18B_Cont_Fe_24h = sd(NaRV.omit(control_18B_24h_Fe$avg_nfoci_0))
Std_ref_18B_Cont_Ar_24h = sd(NaRV.omit(control_18B_24h_Ar$avg_nfoci_0))
Std_ref_18B_Cont_Si_24h = sd(NaRV.omit(control_18B_24h_Si$avg_nfoci_0))
Std_ref_18B_Cont_Gamma_24h = sd(NaRV.omit(control_18B_24h_Gamma$avg_nfoci_0))
#
#
## For Low dose irradiated samples
LD_18B= Samp_18B_10p
LD_18B$avg_nfoci_0=NULL
LD_18B$avg_nfoci_high_dose=NULL
LD_18B$nfoci_high_dose_norm=NULL 
LD_18B$nfoci_low_dose_norm=NULL 
LD_18B$nfoci_0=NULL 
#
### 4h 
LD_18B_4h = LD_18B %>% filter(LD_18B$Timepoint=="4h")
#
LD_18B_4h_Fe = LD_18B_4h %>% filter(LD_18B_4h$Radiation_type=="Fe")
LD_18B_4h_Ar = LD_18B_4h %>% filter(LD_18B_4h$Radiation_type=="Ar")
LD_18B_4h_Si = LD_18B_4h %>% filter(LD_18B_4h$Radiation_type=="Si")
LD_18B_4h_Gamma = LD_18B_4h %>% filter(LD_18B_4h$Radiation_type=="Gamma")
### 24h 
LD_18B_24h = LD_18B %>% filter(LD_18B$Timepoint=="24h")
#
LD_18B_24h_Fe = LD_18B_24h %>% filter(LD_18B_24h$Radiation_type=="Fe")
LD_18B_24h_Ar = LD_18B_24h %>% filter(LD_18B_24h$Radiation_type=="Ar")
LD_18B_24h_Si = LD_18B_24h %>% filter(LD_18B_24h$Radiation_type=="Si")
LD_18B_24h_Gamma = LD_18B_24h %>% filter(LD_18B_24h$Radiation_type=="Gamma")
### For each conditions (radiation type/time point) calculate mean and std
####### Mean
# 4h
Mean_ref_18B_LD_Fe_4h = mean(NaRV.omit(LD_18B_4h_Fe$avg_nfoci_low_dose))
Mean_ref_18B_LD_Ar_4h = mean(NaRV.omit(LD_18B_4h_Ar$avg_nfoci_low_dose))
Mean_ref_18B_LD_Si_4h = mean(NaRV.omit(LD_18B_4h_Si$avg_nfoci_low_dose))
Mean_ref_18B_LD_Gamma_4h = mean(NaRV.omit(LD_18B_4h_Gamma$avg_nfoci_low_dose))
# 24h
Mean_ref_18B_LD_Fe_24h = mean(NaRV.omit(LD_18B_24h_Fe$avg_nfoci_low_dose))
Mean_ref_18B_LD_Ar_24h = mean(NaRV.omit(LD_18B_24h_Ar$avg_nfoci_low_dose))
Mean_ref_18B_LD_Si_24h = mean(NaRV.omit(LD_18B_24h_Si$avg_nfoci_low_dose))
Mean_ref_18B_LD_Gamma_24h = mean(NaRV.omit(LD_18B_24h_Gamma$avg_nfoci_low_dose))
####### sd
# 4h
Std_ref_18B_LD_Fe_4h = sd(NaRV.omit(LD_18B_4h_Fe$avg_nfoci_low_dose))
Std_ref_18B_LD_Ar_4h = sd(NaRV.omit(LD_18B_4h_Ar$avg_nfoci_low_dose))
Std_ref_18B_LD_Si_4h = sd(NaRV.omit(LD_18B_4h_Si$avg_nfoci_low_dose))
Std_ref_18B_LD_Gamma_4h = sd(NaRV.omit(LD_18B_4h_Gamma$avg_nfoci_low_dose))
# 24h
Std_ref_18B_LD_Fe_24h = sd(NaRV.omit(LD_18B_24h_Fe$avg_nfoci_low_dose))
Std_ref_18B_LD_Ar_24h = sd(NaRV.omit(LD_18B_24h_Ar$avg_nfoci_low_dose))
Std_ref_18B_LD_Si_24h = sd(NaRV.omit(LD_18B_24h_Si$avg_nfoci_low_dose))
Std_ref_18B_LD_Gamma_24h = sd(NaRV.omit(LD_18B_24h_Gamma$avg_nfoci_low_dose))
#
#
## For high dose irradiated samples
HD_18B= Samp_18B_10p
HD_18B$avg_nfoci_0=NULL
HD_18B$avg_nfoci_low_dose=NULL
HD_18B$nfoci_low_dose_norm=NULL 
HD_18B$nfoci_high_dose_norm=NULL 
HD_18B$nfoci_0=NULL 
#
### 4h 
HD_18B_4h = HD_18B %>% filter(HD_18B$Timepoint=="4h")
#
HD_18B_4h_Fe = HD_18B_4h %>% filter(HD_18B_4h$Radiation_type=="Fe")
HD_18B_4h_Ar = HD_18B_4h %>% filter(HD_18B_4h$Radiation_type=="Ar")
HD_18B_4h_Si = HD_18B_4h %>% filter(HD_18B_4h$Radiation_type=="Si")
HD_18B_4h_Gamma = HD_18B_4h %>% filter(HD_18B_4h$Radiation_type=="Gamma")
### 24h 
HD_18B_24h = HD_18B %>% filter(HD_18B$Timepoint=="24h")
#
HD_18B_24h_Fe = HD_18B_24h %>% filter(HD_18B_24h$Radiation_type=="Fe")
HD_18B_24h_Ar = HD_18B_24h %>% filter(HD_18B_24h$Radiation_type=="Ar")
HD_18B_24h_Si = HD_18B_24h %>% filter(HD_18B_24h$Radiation_type=="Si")
HD_18B_24h_Gamma = HD_18B_24h %>% filter(HD_18B_24h$Radiation_type=="Gamma")
### For each conditions (radiation type/time point) calculate mean and std
####### Mean
# 4h
Mean_ref_18B_HD_Fe_4h = mean(NaRV.omit(HD_18B_4h_Fe$avg_nfoci_high_dose))
Mean_ref_18B_HD_Ar_4h = mean(NaRV.omit(HD_18B_4h_Ar$avg_nfoci_high_dose))
Mean_ref_18B_HD_Si_4h = mean(NaRV.omit(HD_18B_4h_Si$avg_nfoci_high_dose))
Mean_ref_18B_HD_Gamma_4h = mean(NaRV.omit(HD_18B_4h_Gamma$avg_nfoci_high_dose))
# 24h
Mean_ref_18B_HD_Fe_24h = mean(NaRV.omit(HD_18B_24h_Fe$avg_nfoci_high_dose))
Mean_ref_18B_HD_Ar_24h = mean(NaRV.omit(HD_18B_24h_Ar$avg_nfoci_high_dose))
Mean_ref_18B_HD_Si_24h = mean(NaRV.omit(HD_18B_24h_Si$avg_nfoci_high_dose))
Mean_ref_18B_HD_Gamma_24h = mean(NaRV.omit(HD_18B_24h_Gamma$avg_nfoci_high_dose))
####### sd
# 4h
Std_ref_18B_HD_Fe_4h = sd(NaRV.omit(HD_18B_4h_Fe$avg_nfoci_high_dose))
Std_ref_18B_HD_Ar_4h = sd(NaRV.omit(HD_18B_4h_Ar$avg_nfoci_high_dose))
Std_ref_18B_HD_Si_4h = sd(NaRV.omit(HD_18B_4h_Si$avg_nfoci_high_dose))
Std_ref_18B_HD_Gamma_4h = sd(NaRV.omit(HD_18B_4h_Gamma$avg_nfoci_high_dose))
# 24h
Std_ref_18B_HD_Fe_24h = sd(NaRV.omit(HD_18B_24h_Fe$avg_nfoci_high_dose))
Std_ref_18B_HD_Ar_24h = sd(NaRV.omit(HD_18B_24h_Ar$avg_nfoci_high_dose))
Std_ref_18B_HD_Si_24h = sd(NaRV.omit(HD_18B_24h_Si$avg_nfoci_high_dose))
Std_ref_18B_HD_Gamma_24h = sd(NaRV.omit(HD_18B_24h_Gamma$avg_nfoci_high_dose))

### Now we do the zscore correction on all 18B and 19A
Subject_18BS2_19AS1 = c(1214, 1215,1216,1217,1218,1219,1220,1221,1222,1223)
#
Run_18B = c("Run_18B_Set_2", "Run_18B_Set_1")
Run_19A = c("Run_19A_Set_1", "Run_19A_Set_2", "Run_19A_Set_3", "Run_19A_Set_4")
#
Samp_18B_allp = Corrected_DNA_Damage %>% filter(Corrected_DNA_Damage$Run_set %in% Run_18B)
Samp_19A_allp = Corrected_DNA_Damage %>% filter(Corrected_DNA_Damage$Run_set %in% Run_19A)
#
## For Controls 
Controls_allp_18B= Samp_18B_allp
Controls_allp_18B$avg_nfoci_low_dose=NULL
Controls_allp_18B$avg_nfoci_high_dose=NULL
Controls_allp_18B$nfoci_low_dose_norm=NULL
Controls_allp_18B$nfoci_high_dose_norm=NULL
#
### 4h 
control_allp_18B_4h = Controls_allp_18B %>% filter(Controls_allp_18B$Timepoint=="4h")
#
control_allp_18B_4h_Fe = control_allp_18B_4h %>% filter(control_allp_18B_4h$Radiation_type=="Fe")
control_allp_18B_4h_Ar = control_allp_18B_4h %>% filter(control_allp_18B_4h$Radiation_type=="Ar")
control_allp_18B_4h_Si = control_allp_18B_4h %>% filter(control_allp_18B_4h$Radiation_type=="Si")
control_allp_18B_4h_Gamma = control_allp_18B_4h %>% filter(control_allp_18B_4h$Radiation_type=="Gamma")
### 24h 
control_allp_18B_24h = Controls_allp_18B %>% filter(Controls_allp_18B$Timepoint=="24h")
#
control_allp_18B_24h_Fe = control_allp_18B_24h %>% filter(control_allp_18B_24h$Radiation_type=="Fe")
control_allp_18B_24h_Ar = control_allp_18B_24h %>% filter(control_allp_18B_24h$Radiation_type=="Ar")
control_allp_18B_24h_Si = control_allp_18B_24h %>% filter(control_allp_18B_24h$Radiation_type=="Si")
control_allp_18B_24h_Gamma = control_allp_18B_24h %>% filter(control_allp_18B_24h$Radiation_type=="Gamma")

## z-score correction
# 4h
control_allp_18B_4h_Fe$avg_nfoci_0 = ((((control_allp_18B_4h_Fe$avg_nfoci_0 - Mean_ref_18B_Cont_Fe_4h)/Std_ref_18B_Cont_Fe_4h)
                                      *Std_ref_19A_Cont_Fe_4h) + Mean_ref_19A_Cont_Fe_4h)
                                          
control_allp_18B_4h_Ar$avg_nfoci_0 = ((((control_allp_18B_4h_Ar$avg_nfoci_0 - Mean_ref_18B_Cont_Ar_4h)/Std_ref_18B_Cont_Ar_4h)
                                      *Std_ref_19A_Cont_Ar_4h) + Mean_ref_19A_Cont_Ar_4h) 

control_allp_18B_4h_Si$avg_nfoci_0 = ((((control_allp_18B_4h_Si$avg_nfoci_0 - Mean_ref_18B_Cont_Si_4h)/Std_ref_18B_Cont_Si_4h)
                                      *Std_ref_19A_Cont_Si_4h) + Mean_ref_19A_Cont_Si_4h)
                                          
control_allp_18B_4h_Gamma$avg_nfoci_0 = ((((control_allp_18B_4h_Gamma$avg_nfoci_0 - Mean_ref_18B_Cont_Gamma_4h)/Std_ref_18B_Cont_Gamma_4h)
                                      *Std_ref_19A_Cont_Gamma_4h) + Mean_ref_19A_Cont_Gamma_4h)

# 24h
control_allp_18B_24h_Fe$avg_nfoci_0 = ((((control_allp_18B_24h_Fe$avg_nfoci_0 - Mean_ref_18B_Cont_Fe_24h)/Std_ref_18B_Cont_Fe_24h)
                                      *Std_ref_19A_Cont_Fe_24h) + Mean_ref_19A_Cont_Fe_24h)
                                          
control_allp_18B_24h_Ar$avg_nfoci_0 = ((((control_allp_18B_24h_Ar$avg_nfoci_0 - Mean_ref_18B_Cont_Ar_24h)/Std_ref_18B_Cont_Ar_24h)
                                      *Std_ref_19A_Cont_Ar_24h) + Mean_ref_19A_Cont_Ar_24h) 

control_allp_18B_24h_Si$avg_nfoci_0 = ((((control_allp_18B_24h_Si$avg_nfoci_0 - Mean_ref_18B_Cont_Si_24h)/Std_ref_18B_Cont_Si_24h)
                                     *Std_ref_19A_Cont_Si_24h) + Mean_ref_19A_Cont_Si_24h)
                                          
control_allp_18B_24h_Gamma$avg_nfoci_0 = ((((control_allp_18B_24h_Gamma$avg_nfoci_0 - Mean_ref_18B_Cont_Gamma_24h)/Std_ref_18B_Cont_Gamma_24h)
                                      *Std_ref_19A_Cont_Gamma_24h) + Mean_ref_19A_Cont_Gamma_24h)


## For Low dose irradiated samples
LD_allp_18B= Samp_18B_allp
LD_allp_18B$avg_nfoci_0=NULL
LD_allp_18B$avg_nfoci_high_dose=NULL
LD_allp_18B$nfoci_low_dose_norm=NULL
LD_allp_18B$nfoci_high_dose_norm=NULL
#
### 4h 
LD_allp_18B_4h = LD_allp_18B %>% filter(LD_allp_18B$Timepoint=="4h")
#
LD_allp_18B_4h_Fe = LD_allp_18B_4h %>% filter(LD_allp_18B_4h$Radiation_type=="Fe")
LD_allp_18B_4h_Ar = LD_allp_18B_4h %>% filter(LD_allp_18B_4h$Radiation_type=="Ar")
LD_allp_18B_4h_Si = LD_allp_18B_4h %>% filter(LD_allp_18B_4h$Radiation_type=="Si")
LD_allp_18B_4h_Gamma = LD_allp_18B_4h %>% filter(LD_allp_18B_4h$Radiation_type=="Gamma")
### 24h 
LD_allp_18B_24h = LD_allp_18B %>% filter(LD_allp_18B$Timepoint=="24h")
#
LD_allp_18B_24h_Fe = LD_allp_18B_24h %>% filter(LD_allp_18B_24h$Radiation_type=="Fe")
LD_allp_18B_24h_Ar = LD_allp_18B_24h %>% filter(LD_allp_18B_24h$Radiation_type=="Ar")
LD_allp_18B_24h_Si = LD_allp_18B_24h %>% filter(LD_allp_18B_24h$Radiation_type=="Si")
LD_allp_18B_24h_Gamma = LD_allp_18B_24h %>% filter(LD_allp_18B_24h$Radiation_type=="Gamma")

## z-score correction
# 4h
LD_allp_18B_4h_Fe$avg_nfoci_low_dose = ((((LD_allp_18B_4h_Fe$avg_nfoci_low_dose -Mean_ref_18B_LD_Fe_4h)/Std_ref_18B_LD_Fe_4h)
                                         *Std_ref_19A_LD_Fe_4h) + Mean_ref_19A_LD_Fe_4h)

LD_allp_18B_4h_Ar$avg_nfoci_low_dose = ((((LD_allp_18B_4h_Ar$avg_nfoci_low_dose -Mean_ref_18B_LD_Ar_4h)/Std_ref_18B_LD_Ar_4h)
                                         *Std_ref_19A_LD_Ar_4h) + Mean_ref_19A_LD_Ar_4h)

LD_allp_18B_4h_Si$avg_nfoci_low_dose = ((((LD_allp_18B_4h_Si$avg_nfoci_low_dose -Mean_ref_18B_LD_Si_4h)/Std_ref_18B_LD_Si_4h)
                                         *Std_ref_19A_LD_Si_4h) + Mean_ref_19A_LD_Si_4h)
                                            
LD_allp_18B_4h_Gamma$avg_nfoci_low_dose = ((((LD_allp_18B_4h_Gamma$avg_nfoci_low_dose -Mean_ref_18B_LD_Gamma_4h)/Std_ref_18B_LD_Gamma_4h)
                                         *Std_ref_19A_LD_Gamma_4h) + Mean_ref_19A_LD_Gamma_4h)


# 24h
LD_allp_18B_24h_Fe$avg_nfoci_low_dose = ((((LD_allp_18B_24h_Fe$avg_nfoci_low_dose -Mean_ref_18B_LD_Fe_24h)/Std_ref_18B_LD_Fe_24h)
                                         *Std_ref_19A_LD_Fe_24h) + Mean_ref_19A_LD_Fe_24h)

LD_allp_18B_24h_Ar$avg_nfoci_low_dose = ((((LD_allp_18B_24h_Ar$avg_nfoci_low_dose -Mean_ref_18B_LD_Ar_24h)/Std_ref_18B_LD_Ar_24h)
                                         *Std_ref_19A_LD_Ar_24h) + Mean_ref_19A_LD_Ar_24h)

LD_allp_18B_24h_Si$avg_nfoci_low_dose = ((((LD_allp_18B_24h_Si$avg_nfoci_low_dose -Mean_ref_18B_LD_Si_24h)/Std_ref_18B_LD_Si_24h)
                                         *Std_ref_19A_LD_Si_24h) + Mean_ref_19A_LD_Si_24h)
                                            
LD_allp_18B_24h_Gamma$avg_nfoci_low_dose = ((((LD_allp_18B_24h_Gamma$avg_nfoci_low_dose -Mean_ref_18B_LD_Gamma_24h)/Std_ref_18B_LD_Gamma_24h)
                                       *Std_ref_19A_LD_Gamma_24h) + Mean_ref_19A_LD_Gamma_24h)

## For high dose irradiated samples
HD_allp_18B= Samp_18B_allp
HD_allp_18B$avg_nfoci_0=NULL
HD_allp_18B$avg_nfoci_low_dose=NULL
HD_allp_18B$nfoci_low_dose_norm=NULL
HD_allp_18B$nfoci_high_dose_norm=NULL
#
### 4h 
HD_allp_18B_4h = HD_allp_18B %>% filter(HD_allp_18B$Timepoint=="4h")
#
HD_allp_18B_4h_Fe = HD_allp_18B_4h %>% filter(HD_allp_18B_4h$Radiation_type=="Fe")
HD_allp_18B_4h_Ar = HD_allp_18B_4h %>% filter(HD_allp_18B_4h$Radiation_type=="Ar")
HD_allp_18B_4h_Si = HD_allp_18B_4h %>% filter(HD_allp_18B_4h$Radiation_type=="Si")
HD_allp_18B_4h_Gamma = HD_allp_18B_4h %>% filter(HD_allp_18B_4h$Radiation_type=="Gamma")
### 24h 
HD_allp_18B_24h = HD_allp_18B %>% filter(HD_allp_18B$Timepoint=="24h")
#
HD_allp_18B_24h_Fe = HD_allp_18B_24h %>% filter(HD_allp_18B_24h$Radiation_type=="Fe")
HD_allp_18B_24h_Ar = HD_allp_18B_24h %>% filter(HD_allp_18B_24h$Radiation_type=="Ar")
HD_allp_18B_24h_Si = HD_allp_18B_24h %>% filter(HD_allp_18B_24h$Radiation_type=="Si")
HD_allp_18B_24h_Gamma = HD_allp_18B_24h %>% filter(HD_allp_18B_24h$Radiation_type=="Gamma")

## z-score correction
# 4h
HD_allp_18B_4h_Fe$avg_nfoci_high_dose= ((((HD_allp_18B_4h_Fe$avg_nfoci_high_dose -Mean_ref_18B_HD_Fe_4h)/Std_ref_18B_HD_Fe_4h)
                                         *Std_ref_19A_HD_Fe_4h) + Mean_ref_19A_HD_Fe_4h)

HD_allp_18B_4h_Ar$avg_nfoci_high_dose= ((((HD_allp_18B_4h_Ar$avg_nfoci_high_dose -Mean_ref_18B_HD_Ar_4h)/Std_ref_18B_HD_Ar_4h)
                                         *Std_ref_19A_HD_Ar_4h) + Mean_ref_19A_HD_Ar_4h)

HD_allp_18B_4h_Si$avg_nfoci_high_dose= ((((HD_allp_18B_4h_Si$avg_nfoci_high_dose -Mean_ref_18B_HD_Si_4h)/Std_ref_18B_HD_Si_4h)
                                         *Std_ref_19A_HD_Si_4h) + Mean_ref_19A_HD_Si_4h)

HD_allp_18B_4h_Gamma$avg_nfoci_high_dose= ((((HD_allp_18B_4h_Gamma$avg_nfoci_high_dose -Mean_ref_18B_HD_Gamma_4h)/Std_ref_18B_HD_Gamma_4h)
                                        *Std_ref_19A_HD_Gamma_4h) + Mean_ref_19A_HD_Gamma_4h)
                                          

# 24h
HD_allp_18B_24h_Fe$avg_nfoci_high_dose= ((((HD_allp_18B_24h_Fe$avg_nfoci_high_dose -Mean_ref_18B_HD_Fe_24h)/Std_ref_18B_HD_Fe_24h)
                                         *Std_ref_19A_HD_Fe_24h) + Mean_ref_19A_HD_Fe_24h)

HD_allp_18B_24h_Ar$avg_nfoci_high_dose= ((((HD_allp_18B_24h_Ar$avg_nfoci_high_dose -Mean_ref_18B_HD_Ar_24h)/Std_ref_18B_HD_Ar_24h)
                                         *Std_ref_19A_HD_Ar_24h) + Mean_ref_19A_HD_Ar_24h)

HD_allp_18B_24h_Si$avg_nfoci_high_dose= ((((HD_allp_18B_24h_Si$avg_nfoci_high_dose -Mean_ref_18B_HD_Si_24h)/Std_ref_18B_HD_Si_24h)
                                         *Std_ref_19A_HD_Si_24h) + Mean_ref_19A_HD_Si_24h)

HD_allp_18B_24h_Gamma$avg_nfoci_high_dose= ((((HD_allp_18B_24h_Gamma$avg_nfoci_high_dose -Mean_ref_18B_HD_Gamma_24h)/Std_ref_18B_HD_Gamma_24h)
                                             *Std_ref_19A_HD_Gamma_24h) + Mean_ref_19A_HD_Gamma_24h)




### Now we regroup everything
## regroup 18B

Cont_18B_All_rad= bind_rows(control_allp_18B_4h_Fe,  control_allp_18B_24h_Fe, 
                             control_allp_18B_4h_Ar,  control_allp_18B_24h_Ar,
                             control_allp_18B_4h_Si,  control_allp_18B_24h_Si,
                            control_allp_18B_4h_Gamma,  control_allp_18B_24h_Gamma)

LD_18B_All_rad= bind_rows(LD_allp_18B_4h_Fe,  LD_allp_18B_24h_Fe, 
                          LD_allp_18B_4h_Ar,  LD_allp_18B_24h_Ar,
                          LD_allp_18B_4h_Si,  LD_allp_18B_24h_Si,
                          LD_allp_18B_4h_Gamma,  LD_allp_18B_24h_Gamma)

 HD_18B_All_rad= bind_rows(HD_allp_18B_4h_Fe,  HD_allp_18B_24h_Fe, 
                           HD_allp_18B_4h_Ar,  HD_allp_18B_24h_Ar,
                           HD_allp_18B_4h_Si,  HD_allp_18B_24h_Si,
                           HD_allp_18B_4h_Gamma,  HD_allp_18B_24h_Gamma)


Control_18B_meta_use= Cont_18B_All_rad[,grepl("Sample_ID|Duplicate|Run_set|Timepoint|Radiation_type|avg",colnames(Cont_18B_All_rad))]
#
LD_control_18B=merge(LD_18B_All_rad, Control_18B_meta_use, by=c("Sample_ID", "Duplicate", "Run_set", "Timepoint", "Radiation_type") )
colnames(LD_control_18B)[colnames(LD_control_18B)=="avg_nfoci_low_dose"]<- "RIF"
LD_control_18B$Dose_relative="Low dose"
#
HD_control_18B=merge(HD_18B_All_rad, Control_18B_meta_use, by=c("Sample_ID", "Duplicate", "Run_set", "Timepoint", "Radiation_type") )
colnames(HD_control_18B)[colnames(HD_control_18B)=="avg_nfoci_high_dose"]<- "RIF"
HD_control_18B$Dose_relative="High dose"
#
Cont_18B_All_rad$RIF = Cont_18B_All_rad$avg_nfoci_0
Cont_18B_All_rad$Dose_relative = "0 Gy control"

LD_HD_18B=bind_rows(LD_control_18B, HD_control_18B, Cont_18B_All_rad)



#19A was used as reference: data were not modified. We format the table to fit the same structure as 18B
Samp_19A_allp_LD = Samp_19A_allp
Samp_19A_allp_LD$avg_nfoci_high_dose = NULL
Samp_19A_allp_LD$nfoci_high_dose_norm=NULL
Samp_19A_allp_LD$nfoci_low_dose_norm=NULL
colnames(Samp_19A_allp_LD)[colnames(Samp_19A_allp_LD)=="avg_nfoci_low_dose"]<- "RIF"
Samp_19A_allp_LD$Dose_relative="Low dose"

Samp_19A_allp_HD = Samp_19A_allp
Samp_19A_allp_HD$avg_nfoci_low_dose = NULL
Samp_19A_allp_HD$nfoci_high_dose_norm=NULL
Samp_19A_allp_HD$nfoci_low_dose_norm=NULL
colnames(Samp_19A_allp_HD)[colnames(Samp_19A_allp_HD)=="avg_nfoci_high_dose"]<- "RIF"
Samp_19A_allp_HD$Dose_relative="High dose"


Samp_19A_allp_cont = Samp_19A_allp
Samp_19A_allp_cont$avg_nfoci_low_dose = NULL
Samp_19A_allp_cont$avg_nfoci_high_dose = NULL
Samp_19A_allp_cont$nfoci_high_dose_norm=NULL
Samp_19A_allp_cont$nfoci_low_dose_norm=NULL
Samp_19A_allp_cont$RIF = Samp_19A_allp_cont$avg_nfoci_0
Samp_19A_allp_cont$Dose_relative="0 Gy control"


Samp_plot_19A_allp= bind_rows(Samp_19A_allp_LD, Samp_19A_allp_HD, Samp_19A_allp_cont)

################### regroup 18B and 19A 
All_18B_19A = bind_rows(LD_HD_18B, Samp_plot_19A_allp)

Corrected_step_1_and_2_HT = All_18B_19A
#Corrected_step_1_and_2_CD7 = All_18B_19A

```


```{r}
####### Comparison CD7 VS HT

### After step 1 
# Reformate HT
Corrected_DNA_Damage_HT = Corrected_DNA_Damage_HT %>% filter(Corrected_DNA_Damage_HT$Plate %in% gamma_plate_nums_18B)
Corrected_DNA_Damage_HT_C = Corrected_DNA_Damage_HT[,grepl("Sample_ID|avg_nfoci_0|Plate",colnames(Corrected_DNA_Damage_HT))]
colnames(Corrected_DNA_Damage_HT_C)[colnames(Corrected_DNA_Damage_HT_C) == "avg_nfoci_0"] = "avg_nfoci_HT"
Corrected_DNA_Damage_HT_LD = Corrected_DNA_Damage_HT[,grepl("Sample_ID|avg_nfoci_low|Plate",colnames(Corrected_DNA_Damage_HT))]
colnames(Corrected_DNA_Damage_HT_LD)[colnames(Corrected_DNA_Damage_HT_LD) == "avg_nfoci_low_dose"] = "avg_nfoci_HT"
Corrected_DNA_Damage_HT_HD= Corrected_DNA_Damage_HT[,grepl("Sample_ID|avg_nfoci_high|Plate",colnames(Corrected_DNA_Damage_HT))]
colnames(Corrected_DNA_Damage_HT_HD)[colnames(Corrected_DNA_Damage_HT_HD) == "avg_nfoci_high_dose"] = "avg_nfoci_HT"
#
DD_HT = bind_rows(Corrected_DNA_Damage_HT_C, Corrected_DNA_Damage_HT_LD, Corrected_DNA_Damage_HT_HD)

# Reformate CD7
Corrected_DNA_Damage_CD7 = Corrected_DNA_Damage_CD7 %>% filter(Corrected_DNA_Damage_CD7$Plate %in% gamma_plate_nums_18B)
Corrected_DNA_Damage_CD7_C = Corrected_DNA_Damage_CD7[,grepl("Sample_ID|avg_nfoci_0|Plate",colnames(Corrected_DNA_Damage_CD7))]
colnames(Corrected_DNA_Damage_CD7_C)[colnames(Corrected_DNA_Damage_CD7_C) == "avg_nfoci_0"] = "avg_nfoci_CD7"
Corrected_DNA_Damage_CD7_LD = Corrected_DNA_Damage_CD7[,grepl("Sample_ID|avg_nfoci_low|Plate",colnames(Corrected_DNA_Damage_CD7))]
colnames(Corrected_DNA_Damage_CD7_LD)[colnames(Corrected_DNA_Damage_CD7_LD) == "avg_nfoci_low_dose"] = "avg_nfoci_CD7"
Corrected_DNA_Damage_CD7_HD= Corrected_DNA_Damage_CD7[,grepl("Sample_ID|avg_nfoci_high|Plate",colnames(Corrected_DNA_Damage_CD7))]
colnames(Corrected_DNA_Damage_CD7_HD)[colnames(Corrected_DNA_Damage_CD7_HD) == "avg_nfoci_high_dose"] = "avg_nfoci_CD7"
#
DD_CD7 = bind_rows(Corrected_DNA_Damage_CD7_C, Corrected_DNA_Damage_CD7_LD, Corrected_DNA_Damage_CD7_HD)
#
Corrected_DNA_Damage_HT_CD7 = merge(DD_CD7, DD_HT,by="Sample_ID")


Graph_CD7_vs_HT_correction_step_1 <- ggplot(Corrected_DNA_Damage_HT_CD7, aes(x=avg_nfoci_HT, y=avg_nfoci_CD7)) + geom_point()
Graph_CD7_vs_HT_correction_step_1
ggsave("Step_1_correction_CD7_vs_HT",Graph_CD7_vs_HT_correction_step_1 )


### After step 1 and 2
Corrected_step_2_HT = Corrected_step_1_and_2_HT[,grepl("Sample_ID|RIF|Plate",colnames(Corrected_step_1_and_2_HT))]
colnames(Corrected_step_2_HT)[colnames(Corrected_step_2_HT) == "RIF"] = "avg_nfoci_HT"

Corrected_step_2_CD7 = Corrected_step_1_and_2_CD7[,grepl("Sample_ID|RIF|Plate",colnames(Corrected_step_1_and_2_CD7))]
colnames(Corrected_step_2_CD7)[colnames(Corrected_step_2_CD7) == "RIF"] = "avg_nfoci_CD7"

Corrected_step_1_and_2_HT_CD7 = merge(Corrected_step_2_HT, Corrected_step_2_CD7, by="Sample_ID")

Graph_CD7_vs_HT_correction_step_1_and_2 <- ggplot(Corrected_step_1_and_2_HT_CD7, aes(x=avg_nfoci_HT, y=avg_nfoci_CD7)) + geom_point()
Graph_CD7_vs_HT_correction_step_1_and_2

ggsave("Step_1_and_2_correction_CD7_vs_HT",Graph_CD7_vs_HT_correction_step_1_and_2)



```


