
# This function reads the output average file from Exogen on foci analysis from Loma Linda and generate graphs
# S. Costes, NASA, March 2018
#
```{r}
require('lattice')
require('ggplot2')
require('polynom')
setwd("~/Desktop/PBMC/Sylvains_data")
foci <- read.table('~/Desktop/PBMC/Sylvains_data/summary Loma Linda Dec 2015.txt',sep="\t",header=TRUE)
foci$Radiation = gsub(" ","",toupper(foci$Radiation),fixed = TRUE) # Make all identifier upper case and w/o space
foci$foci_num = as.numeric(as.character(foci$Foci.nuc))
foci$dose = as.numeric(as.character(foci$dose))
foci$time = as.numeric(as.character(foci$time))
                       
keep_ind = foci$time==24

p <- ggplot(foci, aes(dose, foci_num)) 
p <- p + facet_grid(time~Radiation)
p <- p + geom_jitter(width=0.1, height=0, alpha=3/10, shape=21, fill="blue", colour="black", size=1)

print(p)

qplot(dose, foci_num, data=foci, geom=c('boxplot'),color=ID,facets=time~.)
qplot(factor(dose),foci_num, data=foci, geom=c('jitter','boxplot'), color=Radiation)
```


```{r}
# Compute background foci level for each patient and then compute ratio from all other data point
keep_ind = foci$dose==0
mean_bgd_foci = aggregate(foci$foci_num[keep_ind], list(foci$ID[keep_ind]), mean, na.action = na.omit)
colnames(mean_bgd_foci) = c("ID","Foci_Bgd")
foci = merge(foci, mean_bgd_foci, by.x=c('ID'), by.y=c('ID'))
# Eliminate patients with too high background or no background value
keep_ind = foci$Foci_Bgd < 3
foci = foci[keep_ind,]
foci$ratio = foci$foci_num/foci$Foci_Bgd
```

```{r}
# Rank patient sensitivity
keep_ind = foci$dose>0 & foci$time==24 & foci$dose<2
mean_ratio = aggregate(foci$ratio[keep_ind], list(foci$ID[keep_ind]), mean, na.action = na.omit)
mean_num = aggregate(foci$foci_num[keep_ind], list(foci$ID[keep_ind]), mean, na.action = na.omit)
mean_num = mean_num[order(mean_num$x),]
mean_num$patient_sorted = seq(1,13)
colnames(mean_ratio) = c("ID","Avg_ratio")
colnames(mean_num) = c("ID","Avg_foci_dose","Patient_rank")
foci = merge(foci, mean_ratio, by.x=c('ID'), by.y=c('ID'))
foci = merge(foci, mean_num, by.x=c('ID'), by.y=c('ID'))
qplot(Avg_ratio, ratio, data=foci[keep_ind,])

# Classify sensitivity
keep_ind = foci$time==24 & foci$dose<2 & foci$Avg_foci_dose<2
foci$Sensitivity = 2;
foci$Sensitivity[keep_ind]=1
foci$Sensitivity = factor(foci$Sensitivity)
```

```{r}
# Plot ratio
keep_ind = (foci$time==24 & foci$dose<2) & !is.na(foci$Avg_ratio)
qplot(factor(dose),ratio, data=foci[keep_ind,], geom=c('boxplot','jitter'), color=Radiation, width=0.05)
qplot(factor(dose),ratio, data=foci[keep_ind,], geom=c('boxplot','jitter'), size=Avg_ratio, color=Radiation, width=0.05)
qplot(factor(dose),ratio, data=foci[keep_ind,], geom='jitter', color=Avg_ratio, shape= Radiation, size=2, width=0.1, height=0)
qplot(factor(dose),foci_num, data=foci[keep_ind,], geom = c('boxplot','dotplot'), stackdir = "center", binaxis = "y")

foci$Patient_rank = factor(foci$Patient_rank)
keep_ind = (foci$time==24 & foci$dose<2)
theme_set(theme_grey(base_size = 18)) 
keep_ind_gamma = (foci$time==24 & foci$dose<2 & foci$Radiation == "GAMMA") & !is.na(foci$Avg_ratio) 
keep_ind_proton = (foci$time==24 & foci$dose<2 & foci$Radiation == "PROTON") & !is.na(foci$Avg_ratio) 
qplot(factor(dose),foci_num, data=foci[keep_ind,], geom=c('boxplot', 'jitter'), color=Sensitivity, width=0.1, ylim = c(0,5))
summary(foci)
```


# Separating gamma and proton into 2 plots and making a prettier graph
# Egle Cekanaviciute, NASA, March 2018

```{r}
## Dot plot, by type of radiation (gamma or proton). Cancer patients.
dot_by_rad = ggplot(foci[keep_ind,], aes(factor(dose), foci_num)) + geom_point(position = "jitter", aes(color = Sensitivity, shape = Radiation), size = 8) + theme_bw() + theme(axis.text.x=element_text(size=rel(4)), axis.text.y=element_text(size=rel(4)), panel.grid.major = element_line(color = "grey", size = 0.5), axis.line.x = element_line(color = "black", size = 0.5), axis.line.y = element_line(color = "black", size = 1), axis.title = element_text(size=rel(3)), legend.text = element_text(size = rel(2)), legend.title = element_text(size = rel(2))) + scale_color_manual(values = c("black", "red")) + xlab ("Dose, Gy") + ylab ("Average number of foci per nucleus")
dot_by_rad
```

```{r}
## Box and dot plot, radiation types combined. Cancer patients.
boxdot_comb = ggplot(foci[keep_ind,], aes(factor(dose), foci_num)) + geom_boxplot(aes(color = Sensitivity)) + geom_point(position = "jitter", aes(color = Sensitivity, size = 0.5)) + theme_bw() + theme(axis.text.x=element_text(size=rel(4)), axis.text.y=element_text(size=rel(4)), panel.grid.major = element_line(color = "grey", size = 0.5), axis.line.x = element_line(color = "black", size = 0.5), axis.line.y = element_line(color = "black", size = 1), axis.title = element_text(size=rel(3)), legend.text = element_text(size = rel(2)), legend.title = element_text(size = rel(2))) + scale_color_manual(values = c("black", "red")) + xlab ("Dose, Gy") + ylab ("Average number of foci per nucleus")
boxdot_comb
```



```{r}
## Other ideas for separating radiation types

qplot(factor(dose),foci_num, data=foci[keep_ind,], geom=c('boxplot'), color=Radiation, shape=Sensitivity, width=0.1, ylim = c(0,5))
foci$Radiation_sensitivity = paste(foci$Radiation, foci$Sensitivity)
qplot(factor(dose),foci_num, data=foci[keep_ind,], geom=c('boxplot', 'jitter'), color=Radiation_sensitivity, width=0.1, ylim = c(0,5))

qplot(factor(dose),foci_num, data=foci[keep_ind_gamma,], geom=c('boxplot', 'jitter'), color=Sensitivity, width=0.1, ylim = c(0,5), main="GAMMA only")
qplot(factor(dose),foci_num, data=foci[keep_ind_proton,], geom=c('boxplot', 'jitter'), color=Sensitivity, width=0.1, ylim = c(0,5), main="PROTON only")

qplot(factor(dose),foci_num, data=foci[keep_ind,], geom='boxplot', color=Patient_rank, width=0.1, ylim = c(0,5))
qplot(factor(dose),foci_num, data=foci[keep_ind,], geom='jitter', size=Patient_rank, color=Sensitivity, width=0.1, ylim = c(0,5))
```

